compucorp/uk.co.compucorp.manualdirectdebit

manualdirectdebit.php, xml/customFields_install.xml
1. Remove Amount field
2. Add bank_ prefix to address fields. 
3. Set Collection Day as required
4. Add a new empty 'Originator Number' custom group
5. Add a new menu item Administer > Direct Debit > Originator Number. It shows "Direct Debit Originator Number" options.
=> DD-5 fix: Direct Debit Mandate Custom Fields

CRM/ManualDirectDebit/BAO/RecurrMandateRef.php, CRM/ManualDirectDebit/DAO/RecurrMandateRef.php, CRM/ManualDirectDebit/Upgrader.php, manualdirectdebit.php, sql/install.sql, sql/uninstall.sql, xml/customFields_install.xml
1. Add 'dd_contribution_recurr_mandate_ref' custom schema that containing:
- "recurr_id"  field - the id of the recurring contribution that are paid by direct debit
- "mandate_id"  field - the id of the mandate that are used for the recurring contribution
2. Add custom fieldset "Direct Debit Information" that are used for Contributions. The fieldset should have a read-only "mandate_id" field .
=> DD-6: Mandate Reference Fields

settings/ManualDirectDebit.setting.php
1. "New instruction run dates" multi-select field. The options range from 1 to 31.
2. "Payment collection run dates" multi-select field. Now, the options range from 1 to 30.
=> DD-10: Adding direct debt configurations page.

CRM/ManualDirectDebit/Upgrader.php
Billing mode for Payment Processor Type was changed from ‘1’ to ‘2’ for fixing the error in Web Form with wrong required field.
=> DD-12: Updating the DD Payment processor type billing mode to BILLING_MODE_BUTTON

CRM/ManualDirectDebit/Hook/Custom/ContributionDataGenerator.php, CRM/ManualDirectDebit/Hook/Custom/ContributionRecurStartDateGenerator.php, CRM/ManualDirectDebit/Hook/Custom/DataGenerator.php, CRM/ManualDirectDebit/Hook/Custom/MandateDataGenerator.php, CRM/ManualDirectDebit/Hook/MandateContributionConnector.php, CRM/ManualDirectDebit/Hook/PageRun/Contribution/DirectDebitInformation.php, CRM/ManualDirectDebit/Hook/PageRun/TabPage.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, js/hideEmptyMandate.js, manualdirectdebit.php, xml/customFields_install.xml
1. If the user is paying for a membership with "Direct Debit" payment processor via webform, a full direct debit mandate record is added to the contact with the information user filled in.
2. The mandate "DD Ref" is automatically generated if no value is submitted. 
3. The mandate "Start Date" is automatically generated if no value is submitted. 
4. The recurring contribution "Cycle Day" is automatically generated.
5.The recurring contribution "Start Date" is a date on the "Cycle Day" in current month or next month (whichever is the earliest in the future).
6. The first contribution's "Received date" is the recurring contribution "Start Date".
“Collection Day” field is removed from Direct Debit Mandate form
Mandate ID is created and shown only for contributions made with Direct Debit …
=> DD-13: Direct Debit Mandate Generation when submit a Direct Debit Payment from Webform

CRM/ManualDirectDebit/Hook/PageRun/ContributionRecur/DirectDebitFieldsInjector.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, css/directDebitMandate.css, js/directDebitInformation.js, manualdirectdebit.php
1. Add hover and hyperlink style to the Mandate ID on the recurring contribution
2. A Mandate ID is created only when Direct Debit Method is selected
=> DD-6: Adding hover to Mandate ID and  created empty mandate only when Direct Debit Method is selected

manualdirectdebit.php
This PR adds the definition for a new permission called : 
```
Can manage Direct Debit Batches
```
that will be users to allow users to manage direct debit batches.
the machine name for this permission is : 
```
can manage direct debit batches
```
=> DD-19: Adding permission definition for managing direct debt batches

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php, CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Hook/BuildForm/InjectCustomGroup.php, CRM/ManualDirectDebit/Hook/Custom/Contribution/ContributionDataGenerator.php, CRM/ManualDirectDebit/Hook/Custom/Contribution/ContributionRecurStartDateGenerator.php, CRM/ManualDirectDebit/Hook/Custom/DataGenerator.php, CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php, CRM/ManualDirectDebit/Hook/MandateContributionConnector.php, CRM/ManualDirectDebit/Hook/PageRun/ContributionRecur/DirectDebitFieldsInjector.php, CRM/ManualDirectDebit/Hook/PageRun/TabPage.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, CRM/ManualDirectDebit/Hook/PostProcess/Membership/DirectDebitMandate.php, CRM/ManualDirectDebit/Hook/PostSave/MembershipPayment/MandateCreator.php, CRM/ManualDirectDebit/Hook/ValidateForm/MandateValidator.php, manualdirectdebit.php, settings/ManualDirectDebit.setting.php, templates/CRM/ManualDirectDebit/Form/InjectCustomGroup.tpl
1. Inject the following functionality on admin "New membership" and "Renew Membership" screens so that when the admin records a contribution or payment plan with payment method "Direct Debit", a set of mandate fields will appear underneath the contribution and payment plan section.
2. The "Start Date" field should be automatically adjust according to "Payment Plan Start Date" minus "Minimum days from new instruction to first payment". However, user can also manually change this.
3. Once submitted successfully, a mandate should be generated and the mandate should be linked to both contributions and payment plans (if applicable).
- Creating Mandate for DD contribution from New Membership 
- Creating Mandate for DD contribution from Renew Membership
=> DD-22: Create mandate for Direct Debit contributions on Admin screens

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Hook/PageRun/TabPage.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, CRM/ManualDirectDebit/Upgrader.php, js/hideEmptyMandate.js, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl, templates/CRM/ManualDirectDebit/Page/BatchList.tpl
1. Fix batch mechanism- Batch keeps a snapshot of the data at the time when the batch is created.
2. Add pagination to the View New Instruction Batches and View Payment Batches pages
3.View link goes to:
-to view the mandate on the contact page - View New Instruction Batches
-the contribution on the contact page - View Payment Batches 
4. Add a new menu item “Direct Debit”
=> DD-18/19: Fix wrong batch mechanism, pagination and view link

CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php, CRM/ManualDirectDebit/Hook/BuildForm/CustomDataByType.php, js/mandateEdit.js, manualdirectdebit.php
1. Hide the "Edit Direct Debit Mandate" button.
2. Replace the "Delete" button on each Direct Debit Mandate with an "Edit" button that allows each Direct Debit Mandate to be edited.
3. Once clicked on the "Edit" button on a Direct Debit Mandate, a modal including all mandate fields should appear which allows the admin to modify the mandate information.
=> DD-23: Manage mandate buttons

CRM/ManualDirectDebit/Hook/BuildForm/CustomDataByType.php
- The contribution custom fields do not disappear in edit mode when the Direct Debit extension is enabled
=> DD-6 fix: The contribution custom fields do not disappear in edit mode when the Direct Debit extension is enabled

CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchTableListHandler.php, CRM/ManualDirectDebit/Page/BatchTransaction.php
Even if the user have "**Can manage Direct Debit Batches**" permission, he still cannot see any batch inside "View New Instruction Batches"  and "View Payment Batches" pages when there is a direct debt batches. 
The batch pages were using the following core method : 
CRM_Batch_BAO_Batch::getBatchList($param);
to get the list of batch rows and view them in the table.
But this method only bring results back in case the user has either "view own manual batches" or "view all manual batches" permissions.
I created a new class **CRM_ManualDirectDebit_Page_BatchTableListHandler**   that replace the core method and ensure that the results are fetched correctly if the user have "**Can manage Direct Debit Batches**".
=> DD-39: Ensure that (manage direct debit batches) is used correclty

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php, CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, js/mandateEdit.js, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/SendMandateNotification.tpl
1. A "Send mandate update notification to the contact?" checkbox is added to the bottom of the "Edit Direct Debit Mandate Record" modal (edit mandate directly) and "New Direct Debit Mandate Record".
2. Adding a postprocessing in the extension so when any change is made to an existing mandate or when a new mandate is used for an existing recurring contribution, a "Direct Debit Mandate Update" activity is generated
=> DD-31: Mandate update activity

CRM/ManualDirectDebit/BAO/RecurrMandateRef.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php
1- When there is more than one dd mandate ref linked to a recurring contribution via dd_contribution_recurr_mandate_ref table, on the view recurring contribution screen, the first mandate is shown.
2- When assigning a new mandate for a recurring contribution, the already completed (paid) contributions mandate reference will change to point to the last assigned mandate.
1- When there is more than one dd mandate ref linked to a recurring contribution via dd_contribution_recurr_mandate_ref table, on the view recurring contribution screen and related contributions view screen, the last linked mandate is shown.
2- When assigning a new mandate for a recurring contribution, the already completed (paid) contributions related to the recurring contribution are now showing the mandate used at the …
=> DD-43: Mandate reference  improvement

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php
When viewing or exporting "New instruction"  or "Direct Debit payment", then amounts are showing as is, so if the value is 0 then it will appear as 0, if it 5.3 then it will appear as 5.3
All amounts are now showing 2 decimal places, so if the value is 0 then it will appear as 0.00 , if it 0.1 then it will appear as 0.10, if it 5.3 then it will appear as 5.30, if 5.34 then it will appear as 5.34 .
=> DD-47: Make Batch export amounts always have 2 decimal places

CRM/ManualDirectDebit/Form/BatchTransaction.php, templates/CRM/ManualDirectDebit/Page/BatchTransaction.tpl
In export batch pages, we had only one button called "Done and Export Batch" that both save then export the batch.
A new button is added called "save" that only save the batch and redirect to view batches list page, and "Done and Export Batch"  button is renamed to "Save and Export Batch" that both save the batch and export the batch.
=> DD-45: Add save button to batch export pages

CRM/ManualDirectDebit/Upgrader.php, settings/ManualDirectDebit.setting.php, templates/CRM/ManualDirectDebit/Form/Configurations.hlp
In this PR I : 
1- I've renamed 'Minimum prefix reference length' setting field to 'Minimum mandate reference length' 
2- I'v added a help text to the field that explains its purpose.
3- I'v added an upgrader that sets the 'Minimum mandate reference length'  field default value for existing sites.
=> DD-44: Improvements and fixes

CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php
We where applying the Minimum mandate reference length setting on the mandate id part only and ignoring the prefix, so for example if the prefix = 'M' and Minimum mandate reference length  = 6 and the mandate ID = 65 then the generated mandate reference will be : 
```
M000065
```
so the total reference mandate as you can see above is 7 and not 6 which makes the Minimum mandate reference length concept confusing to the user.
The calculation is fixed to also take the prefix  itself length  into the account, so using the example above, the generated mandate reference will be : 
```
M00065
```
=> DD-44: Update the mandate refernce calculation so it also take effect on the prefix too

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/PostProcess/Membership/DirectDebitMandate.php
The code initialize MySQL transaction before certain operations but never commit it on success, the PR ensure that all successful transactions get committed so the data get actually stored.
=> BASW-194 : Ensure that all open transactions will be committed on success

CRM/ManualDirectDebit/Hook/PostOfflineAutoRenewal/Mandate.php, manualdirectdebit.php
Upon offline auto-renewal and in case that the membership is originaly paid using payment plan , then the newly created recurring contribution created due to the auto-renewal will not have a link to the previous mandate in case there was a mandate.
The recurring contribution will link to the same mandate as the previous recurring contribution.
=> BASW-211: Link the mandate to the new offline auto-renewal recurring contribution

js/mandateEdit.js
This PR contains HTML fix for edit button so that it picks the default civicrm edit button styles.
***Note**:This change is encouraged from the changes requested in SPAB-832 (https://compucorp.atlassian.net/browse/SPAB-832).*
=> SPAB-832: Fix markup for edit DD mandate button

CRM/ManualDirectDebit/Upgrader.php
If the site does not have a financial account  type called '**Deposit Bank Account**' then it will cause problems during the extension installation.
I removed the financial account type parameter during the creation of "Direct Debit" (PP) payment processor.
=> BASW-169: Removing the financial type from the DD payment processor

CRM/ManualDirectDebit/Upgrader.php
We need to check the extension's process to see if any of the scheduled jobs created by the extension are automatically turned on during the installation process.
We need to make sure all scheduled jobs created by these extensions are turned off by default.
Jobs created by this extension were enabled by default after installation on some setups because `'0'` is being passed to `is_active` as a string instead of as an integer
Jobs created by the extension are now disabled on extension installation on all setups.
=> ASE-257: Ensure Created Jobs are Disabled

CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php
Currently mandate ref field is hidden from all forms, e.g. new membership form, use a new mandate form and edit mandate form.
We want to expose the mandate ref field on edit mandate form so after a mandate is created, staff can manually edit the mandate ref afterwards.
I altered CRM_ManualDirectDebit_Hook_BuildForm_CustomDatar::run() method  to stop calling hideDdRef() method that hides the mandate reference field.
=> DD-59: Allow users to edit the mandate ref from UI

CRM/ManualDirectDebit/Batch/BatchHandler.php
In DD process, when submitting a payment collection batch, all contributions in the batch will be set to "Completed" status. However, if any of the contributions are linked to a pending membership, the membership is not getting activated. It should!
Contribution status change was being updated via a query directly sent to the DB, hence none of the business logic associated to status change was being executed.
Fixed by calling API to update the contribution status and adding a call to CRM_Contribute_BAO_Contribution::transitionComponentWithReturnMessage(), which does the actual work of updating related entities on status change.
=> BASW-147: Mandate Submission Should Update Membership Status

CRM/ManualDirectDebit/Common/MessageTemplate.php, CRM/ManualDirectDebit/Event/Listener/TokenRender.php, CRM/ManualDirectDebit/Mail/DataCollector/Base.php, CRM/ManualDirectDebit/Mail/Notification.php, CRM/ManualDirectDebit/Upgrader.php, templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentCollectionReminder.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentSignUpNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentUpdateNotification.tpl, xml/DDTemplate_customgroup.xml
The following improvements and fixes are done to  the DD message templates : 
- When the payment plan’s number of installment is less than 2 (null, 0, 1), the order summary is now showing only the last installment into calculation.
- When the payment plan’s number of installment is less than 2 (null, 0, 1), the payment schedule  is now showing only the last installment.
- Support for pricefields payments with more than one membership is added.
- New smarty variable is added that show all the current active memberships for the contact.
----------------------------------
A new custom group called **Direct Debit** is added to the **MessageTemplate** entity which contains two fields : 
1- is_direct_debit_template : if 1 then the template will be considered a direct debit template and it will …
=> DD-58: Improvments and fixes to DD message templates data and format

CRM/ManualDirectDebit/Batch/BatchHandler.php
When submitting a payment instruction patch for more than one recurring contribution, only one recurring contribution will be submitted.
This was caused by a typo in a variable name inside getMandateCurrentState() method which is fixed and now the submission work correctly.
=> ASE-271: Ensure that all recur contributions get submitted  correctly for payment instruction batch

CRM/ManualDirectDebit/Batch/Transaction.php
Any records associated with deleted contacts (soft delete) should not be available to be selected when creating a new Instruction batch. Any test contributions should not available to be selected when creating a new payment collection batch.
Deleted contacts and test contributions were being shown on payment and instruction batches to be selected.
Added where clauses and joins to filter out deleted contacts and test contributions.
=> DD-60: Filter Out Deleted Contacts and Test Contributions from Batches

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Mail/DataCollector/Base.php, api/v3/ManualDirectDebit.php, js/mandateEdit.js
We need to implement the option to delete mandates. Also, when sending notifications relate to direct debit mandates, the account number should be obfuscated, replacing all but the last 4 characters with asterisks.
The button to delete mandates was hidden. Account number sent on e-mail notifications was sent complete, posing obvious security risks.
The button to delete is now shown and re-styled to match the edit button. Clicking it calls  new API action that deletes the mandate and all related records.
When data is collected from mandates to be used on DD notifications, account number is obfuscated by replacing all but the last 4 numbers to the '*' character.
=> ASE-272: Implement Deletion of Mandates and Hide Account Number on Notifications

CRM/ManualDirectDebit/Batch/Transaction.php
1- Create a new payment batch with say 3 items
2-  Create new payment batch page
3- Then discard the payments batch
4- Creating a new payment batch with the 3 items above and check the no. of available payments now, it will 6 instead of 3.
I changed the query that used for both fetching the batch items as well as counting the items to return distinct items. It was only enforced on instruction batches before so I changed it to be applied for both instruction and payment batches.
=> DD-61: Fix payment batches pagination count

CRM/ManualDirectDebit/Batch/Transaction.php
This Reverts compucorp/uk.co.compucorp.manualdirectdebit#88 since this solution might affect payment plan batches in a bad way.
=> Revert "DD-61: Fix payment batches pagination count"

CRM/ManualDirectDebit/Batch/Transaction.php
In this PR I reapplied the patch that I reverted here : https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/90
since after a call with Guanhuan he said that it might not correct for payment patches where a recurring contribution have more than one contribution in the past. I went through the code again and did some tests and validation and this fix is actually correct and won't cause any issues in such case.
=> DD-61: Fix creating payment batch pagination count after discarding it

CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php
On this PR https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/81 , I make it available for users to edit the DD reference field per requirements . But it apparently  now also show the field even for all the mandate forms even the Add form, but this should not be the case since for adding mandate, the reference should be generated automatically. This PR fixes this so the DD reference field is hidden if we are adding a mandate.
=> DD-59: Ensure that the DD refernce field is hidden on add form

CRM/ManualDirectDebit/Common/MandateStorageManager.php
When signing up for membership with direct debit payment method and then if you choose the start date as another day (ie not today) and then save, the mandate is created with today as start date.
When creating a mandate, insertion into the database was done using a manual INSERT query, and then the civicrm_custom hook was launched so other mandate fields were generated. This hook requires a third parameter, which is a list of the fields and their values in a very specific format with all the fields'
meta data. This format was not being used when calling the hook.
Fixed by replacing the simple [$field => $value] array with another built with the expected format.
=> ASE-299: HOTFIX! Fix Mandate Creation with Start Date Different to Actual Date

CRM/ManualDirectDebit/Common/MandateStorageManager.php
When signing up for membership with direct debit payment method and then if you choose the start date as another day (ie not today) and then save, the mandate is created with today as start date.
This is a cherry-pick of fix merged to master branch on PR #96 
When creating a mandate, insertion into the database was done using a manual INSERT query, and then the civicrm_custom hook was launched so other mandate fields were generated. This hook requires a third parameter, which is a list of the fields and their values in a very specific format with all the fields'
meta data. This format was not being used when calling the hook.
Fixed by replacing the simple [$field => $value] array with another built with the expected format.
=> ASE-299: Fix Mandate Creation with Start Date Different to Actual Date

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Form/Mandate/Create.php, CRM/ManualDirectDebit/Hook/BuildForm/Payment.php, CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, CRM/ManualDirectDebit/Hook/PostProcess/Membership/DirectDebitMandate.php, js/paymentMethodMandateSelection.js, manualdirectdebit.civix.php, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/Mandate/Create.tpl, templates/CRM/ManualDirectDebit/Form/Payment.tpl, xml/Menu/manualdirectdebit.xml
Currently on "New Membership" and "Renew Membership" forms, when Direct Debit is selected as the payment method, a mandate fieldset that allows admin to creating a new mandate, appears on the form. This does not happen on any other back-office payment recording pages.
Whenever Direct Debit is selected as the payment method, a dropdown list with the existing mandates of the contact should appear so admin can select one of the existing mandates or create a new mandate for the payment.
The mandate dropdown should list all existing mandates of a contact plus a "Create New..." option. All existing mandates options should be listed in the format of "MANDATE_REF - DD_CODE - A/C_NO - START_DATE".
Creation of a membership showed fields to create a mandate, when DD payment method was chosen. Other …
=> DD-64: Implement Mandate Selection When Choosing Payment Method

CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php
When creating a mandate, its reference should be generated by the system by concatenating a prefix set by the admin with a consecutive number (the mandate's ID).
The reference was always set to "DD Ref" on the mandate creation form on a hidden field. This cause the mandate reference to not get generated from the prefix and the mandate id.
Fixed so if the mandate corresponds to "DD Ref", it is overwritten by a string generated by the system.
=> DD-64: Implement Auto-selection of Created Mandate

CRM/ManualDirectDebit/Mail/Task/MembershipEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/PDFLetterCommon.php
When trying to export a Direct Debit PDF letters from "membership search" action, and if there is at least one membership that cannot be exported then a notification will appear with the following message : 
```
No Letters were generated for the membership(s) with the following Id(s): XXX-1, XXX-2 ..etc
```
But the problem is that since there is a file that will be downloaded, the notification will only appear after moving to different civicrm page or refreshing the same page manualy, and it is really hard to do a refresh for the page after downloading automatically without reworking major parts of how civicrm handles pdf exports.
Instead of showing a notification, We now log the message to civicrm logs file,  and if "Enable Drupal Watchdog Logging" option is enabled, it will also show in …
=> ASE-306: Log failed membership Ids instead of showing them in a notification

CRM/ManualDirectDebit/Hook/BuildForm/Payment.php, CRM/ManualDirectDebit/Hook/BuildForm/UpdateSubscription.php, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/Payment.tpl
When editing a recurring contribution, you can see the selected payment method and change it. When the payment method used by a recurring contribution is Direct Debit, the mandate selection box is also loaded. However, the mandates box does not show the mandate that had been already associated to the recurring contribution.
Editing a recurring contribution with Direct Debit as a payment method loaded the mandate selection box, but was loading the box for the currently logged in user, instead of the contact that was being worked on.
When the recurring contribution edit form is loaded, an ajax call is made to load the fields associated to the payment method that was chosen. This call sends the contact_id if it is set in CRM.vars.coreForm.contact_id. If it is not set, CiviCRM attempts to …
=> DD-64: Preload Selected Mandate on Recurring Contribution Edit Form

CRM/ManualDirectDebit/Common/CollectionReminderSendFlagManager.php, CRM/ManualDirectDebit/Hook/Post/Contribution.php, CRM/ManualDirectDebit/ScheduleJob/Reminder.php, CRM/ManualDirectDebit/ScheduleJob/TargetContribution.php, CRM/ManualDirectDebit/Upgrader.php, manualdirectdebit.php, xml/collectionReminderSendFlag_customgroup.xml
Every time the "Send Direct Debit Payment Collection Reminders" job is executed, it will find any contribution that meets all criteria below:
- Payment Method is Direct Debit
- Contribution Status is Pending or Cancelled
- Receipt Date is empty
- "Received Date" minus "Days in advance for Collection Reminder" is equal to or smaller than today.
And send an email for the contact which matches the criteria above every time the scheduled job runs, Which will result in keep sending the same email over and over to the same contact each time the job runs .
I added a new contribution custom group called "Collection Reminder Send Flag" which contains a single Boolean field called "Is Collection Reminder Notification sent ?".
Whenever a contribution is now created, the field will be set to False …
=> DD-77: Ensure that the collection reminder get sent only once for each contribution

CRM/ManualDirectDebit/ScheduleJob/TargetContribution.php
Suppose we have the following scenario : 
```
today date is : 24/5/2019
There are 4 contribution with the following 
receive dates : 
1- 24/6/2019
2- 24/7/2019
3- 24/8/2019
4- 24/9/2019
If "Days in advance for Collection Reminder " is configured to be 10 days, then the contact must receive an email for every contribution above at the following dates  respectively : 
1- 14/6/2019-10
2- 14/7/2019-10
3- 14/8/2019-10
4- 14/9/2019-10
```
but that was not the case, the current code was sending them in the eample above 10 days after the received date and not before.
I altered the query that fetch the list of collection reminder contirbution to match the correct condition which is : 
```
Contribution "receive date" Minus  "Days in advance for Collection Reminder" is less or Equal today date.
```
=> DD-77: Ensuring that collection reminders get send before the configured day and not after

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Page/AJAX.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
**Overview**
This PR solves a few issues regarding contribution filters and receive date column on direct debit batch pages.
**DD-72: Fetch direct_debit option value dynamically** 
Earlier, it was a bad idea to use static option value for the option generate by an extension. It selected a different payment method on the dev site because the option values where different. This commit sorts that out.
**DD-72: Set end date to today's date only when user chooses 'Choose Date Range' option**
We are now allowing all date options for the filters.
**DD-72: Only Add receive column for dd payments batch page 
DD-72: Only add receive_date for dd_payments batch types**
"Received date" columns is now visible only on dd payment create page and not on instructions page.
=> DD-72: Refining logics on newly added contribution filters.

manualdirectdebit.php
**Overview**
When dd mandate was edited and saved, it updated receive date from the last contribution installment. As a result, the installment was collected at a wrong date.
This PR makes sure that contribution don’t get updated when dd mandate is edited.
**Before**
Contribution date was updated when dd mandate was edited.
**After**
Contribution date doesnt update when dd mandate is edited.
**Technical Details**
Below is the code that caused this issue. The runDataGeneration was run on both create and edit of mandate. This function generates date was contributions too. It should run on generateMandateData() method when dd mandate is edited.
```php
function manualdirectdebit_civicrm_custom($op, $groupID, $entityID, &$params) {
if …
```
=> ASESPRT-119: Prevent contribution date from updating when editing dd mandate

xml/customFields_install.xml
When trying to install the extension on CiviCRM 5.19 the following fatal
error appears :
"A fatal error was triggered: One of parameters (value: ) is not of the type Integer"
The error caused by the following line in CiviCRM core :
https://github.com/civicrm/civicrm-core/blob/cbaa9a31f02afda8d2e19610da823fd0c4d28a16/CRM/Utils/Migrate/Import.php#L163
The method in which the line above exist is the one responsible for
processing any option value defined in the extension XML files, the
method first check if the option group for which the option value belong
is defined in the XML file itself and if not it try to look it up in
already defined CiviCRM option groups, this line is responsible for the
latter and it passes "$optionValueXML->option_group_name" to
getFieldValue() method but since …
=> CGP-1492: Fixing Installation failure on CiviCRM 5.19

CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php
When trying to create a DD batch (either an instruction batch or a payment collection batch) then a fatal error will appear that prevents the user to do so.
Creating DD batches work fine : 
Whan trying to create an Instruction batch or a Payment collection
batch, the following fatal error will appear after the user select the
batch name and originator number and clicking Next :
Error: Call to undefined method CRM_ManualDirectDebit_Form_BatchTransaction::addSearchFieldMetadata() in CRM_Contribute_BAO_Query::buildSearchForm
which prevent the user from creating the batch and exporting it.
The error caused by the following line inside
CRM_ManualDirectDebit_Form_BatchTransaction class :
CRM_Contribute_BAO_Query::buildSearchForm($this);
The line above pass an instant of the current form object …
=> MAE-84: Fixing an error that prevented users from creating DD batches

templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentCollectionReminder.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentSignUpNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentUpdateNotification.tpl
In message templates and under Direct Debit Guarantee section, we had a  placeholder text.
The placeholder text is replaced with the actual Direct debit guarantee
Hence since that existing organisations (users) already have this text updated, no upgrader is added to update this and this will only work for new installations.
=> MAE-19: Update the placeholder text with Direct Debit Guarantee in message templates

CRM/ManualDirectDebit/Hook/ValidateForm/MandateValidator.php, js/paymentMethodMandateSelection.js, manualdirectdebit.php
When creating a membership and paying for it using Direct Debit, a field to select/create the mandate is shown. If this field is left empty and the membership saved, the system will start processing the form and end in a screen with a fatal error.
Membership creation form was allowing mandate field to be empty when Direct Debit was selected as payment method. This caused a fatal error to be thrown when saving the membership.
Fixed by validating mandate is not empty if direct debit payment method has been chosen. Also added some js logic to leave the membersip creation form in a consistent state after a failed validation, as contact_id and the mandate field were being lost.
=> CGP-1472: Implement Validation of Mandate Field on Membership Creation

CRM/ManualDirectDebit/Mail/Task/ContributionEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/MembershipEmailCommon.php
1. Login as admin
2. Use 'Find memberships' or 'Find Contribution' search 
3. Select a few memberships/or contributions and then select Actions / Send Direct Debit Notifications
4. On next screen select the from email address to be something else than the logged in user's email address
5. Select one of the DD templates
6. Send the email
7. Check the email and see which email address the email was sent FROM - its the logged in user's email address instead of the one that you selected.
The selected user in step 4 above will be the one used in the "From" when sending the email instead of the logged in user.
The issue happen because some changes in core forms that you can see below, and since the DD send notifications search actions where written on top of civicrm core functionally, the …
=> MAE-68: Pick the correct sender email when sending direct debit emails

templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
When Shoreditch extension is enabled, the "Added to batch" sub-header on batch edit pages will appear as the following and block the save and export buttons :
While without  Shoreditch extension it looks fine: 
And here it is without Shoreditch :
=> MAE-162: Fix the sub-header of batch edit screen on Shoreditch

templates/CRM/ManualDirectDebit/Page/BatchList.tpl
When there are more than 50 batch (either a payment or an instruction batch), then the list view (table) page will show a duplicate pagination control as following : 
Only one pagination control appears in the page : 
The DD batch list pages are doing both CiviCRM backed pagination and also Datatables JS plugin pagination,.
The issue happen for > 50 records because CiviCRM backend pagination have a default value of 50 row per page, so when there are more than 50 records (let's say 55 records) CiviCRM backed pagination will split the records into two pages, and because we also have Datatables pagination with default records per page set to 10 (which is the default Datatables records per page number) then Datatables will split the first CiviCRM page with 50 records into 10 pages and the 2 …
=> MAE-95: Fix duplicate pagination issue in DD batch list pages

CRM/ManualDirectDebit/Hook/ValidateForm/MandateValidator.php, CRM/ManualDirectDebit/Mail/Task/PDFLetterCommon.php, js/paymentMethodMandateSelection.js
1- If the '- Select -' option was not changed  when paying using direct debit then a validation message should appear asking the user to select a mandate 
but currently the page will just hang.
2- When creating a mandate, it will be added to the current logged in user instead of the contact that we are creating the mandate for.
3- Printing direct debit letters will throw "Invalid Response" http error.
1- the `- Select- ` option value is `-` , but the validation code checks for empty value, so I just fixed the code to also check for `-` and show the validation message if the  `- Select- ` option is selected.
2- 
When creating a membership from the membership tab , the `contact_id` element does not exist but still it was calling the following lines 
```
if (contactField.val() !== ""  && …
```
=> MAE-76: Fixing issues with creating mandates and printing mandate letters

CRM/ManualDirectDebit/Hook/MandateContributionConnector.php
When creating a membership signup webform with Direct debit enabled on it, the created contribution(s) and recur contribution will not have the created mandate linked to them.
It seems that the issue started after this PR : 
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/112/files
When this line is called : 
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blob/36886717a2709d308d38fd70c63c939144edb36d/CRM/ManualDirectDebit/Hook/Post/Contribution.php#L18
it will call CiviCRM contribution API to update a certain custom field on the contribution, which will trigger this hook : manualdirectdebit_civicrm_postSave_civicrm_contribution()  with only the contribution ID and that custom field value, 
the hook above will call this method …
=> CGP-1507: Fix missing mandate Id on contribution and recur contribution after webform submission

js/mandateEdit.js, templates/CRM/ManualDirectDebit/Form/InjectDirectDebitInformation.tpl
When Shoreditch theme is enabled and When Trying to edit a mandate
or create a new mandate for the recur contribution : 
then the save and cancel buttons do not appear.
Here how things look now for edit mandate page  : 
And for "using new mandate" I had to make it open in a new page since it will be time consuming to make it work inside a modal : 
I had to change the links to open the mandate forms so the href attribute  contains the link to edit the mandate instead of using onclick even listener and CRM.loadPage()
=> MAE-164: Make save button avaliable when editing mandate

CRM/ManualDirectDebit/Hook/BuildForm/Membership.php, CRM/ManualDirectDebit/Hook/ValidateForm/MandateValidator.php, js/paymentMethodMandateSelection.js
'Mandate' field is not highlighted, when Warning message is shown. After form validation.
Furthermore, on Contact's new membership and renew membership modal dialogs, after failed validation the mandat field is not shown, and you need to select another payment instrument and reselect Direct Debit in order to load the mandate id field.
Since mandate field is loaded after the membership forms are, CiviCRM wasn't able to mark the field as an error.
Also, on modal dialogs, since the page is not refreshed, events to re-load mandate ID field are not triggered.
Added a global JS variable set by back.end validation in order to be able to check if mandate field has been sent empty. So now the mandate dield is marked with appropriat CSS classes to be shown as an error.
Also captured CiviCRM dialog …
=> CGP-1472: Handle Mandate ID Validation Errors on Membership Forms and Dialogs

CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php
Default of todays date not being set if left blank or not enabled on Webform for Mandate's authorization date.
When mandate was created through webform, if the authorization date field was left empty, hidden, or simply not included in the webform, the mandate was being created with wmpty authorization date.
Implemented check of empty value for authorization date field, and set to current date if found empty.
=> MAE-187: Set Current Date as Default Value for Authorization Date

CRM/ManualDirectDebit/Hook/Custom/DataGenerator.php
Changing a recur contribution (payment plan) to use new mandate will result in changing the recur contribution start date and cycle day, it will also result in changing the last contribution receive date.
And while we may need to think on how to handle this in the future, for now we need only to change the recur contribution to point to the new mandate without touching the dates.
Changing the recur contribution mandate is only affecting the mandate that the recur contribution is linked to and does not the dates.
When using "using new mandate" button to change the payment plan mandate, a new form will be opened that after get submitted will both create and assign the mandate to the payment plan, where in places such as the membership form the mandate is created first in a separate form …
=> IOSPRT-35: Prevent changing payment plan cycle day when using new mandate

CRM/ManualDirectDebit/Upgrader.php
Users are unable to send DD emails on sites created using Compuclient.
For some reason,  the database that is used for creating Compuclient sites does not have the direct debit message templates related custom fields set which are needed in order for such emails to be sent.
I added a new upgrader that will set these fields for existing sites if there are not already set.
=> MAE-226: Fix sending DD emails on Compuclient sites

CRM/ManualDirectDebit/BAO/RecurrMandateRef.php, CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/DAO/RecurrMandateRef.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, CRM/ManualDirectDebit/Hook/PostProcess/RecurContribution/DirectDebitMandate.php, manualdirectdebit.php
1- Changing the mandate from the recur contribution edit form  will not actually change the mandate.
2- a new mandate reference record is created inside `dd_contribution_recurr_mandate_ref` table (whichstores the reference between the mandate and the recur contribution) every time the user change the mandate
1- Changing the mandate from the recur contribution edit form is now reflected on the recur contribution.
2- only one mandate reference is now getting created per recur contribution and it will get updated if the user change the recur contribution mandate. 
- Some unused methods are removed
- the copyValues() method inside CRM_ManualDirectDebit_DAO_RecurrMandateRef  class was unnecessarily overridden, so I removed it.
=> IOSPRT-34: Fixes to manual mandate update

CRM/ManualDirectDebit/Hook/Links/LinkProvider.php, CRM/ManualDirectDebit/Hook/PageRun/ContributionRecur/DirectDebitFieldsInjector.php, js/mandateEdit.js, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/InjectDirectDebitInformation.tpl
Trying to edit a mandate for a contact that belongs to an organisation sub-type (such as Team subtype)  will result in the following error : 
```
CRM_Core_Exception: Invalid Entity Filter civicrm/CRM/Core/BAO/CustomGroup.php on line 489
CRM_Core_BAO_CustomGroup::validateSubTypeByEntity('Individual', 'Team')
```
Editing a mandate for a contact that belongs to any subtype is working normally whether it from the recur contribution view page or "use new mandate" button.
The error occurs because the mandate edit link that is generated by the extension always have `Individual` as the contact type in the URL GET parameters, e.g : 
```
/civicrm/contact/view/cd/edit?reset=1&type=Individual&groupID=23&entityID=226&cgcount=1&multiRecordDisplay=single&mode=edit&mandateId=96&snippet=json
```
and since …
=> ASESPRT-216: fix editing mandate for orgnisation sub-type contacts

CRM/ManualDirectDebit/Hook/BuildForm/UpdateSubscription.php, templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl
There are some issues when users are changing the payment plan (recur contribution) payment method from Direct debit to something else or vice versa, such as the created mandate when changing the payment method to DD is not getting linked to the related contributions , And since fixing these issues might take sometime we decided to hide the ability to change the payment method of the recur contribution if the it is already Direct Debit, and to hide the Direct Debit payment method if the payment method is already something else (such as  Cash).
EFT Payment method is selected, the Direct debit payment method is not appearing as a payment method : 
Direct debit is the payment method for this Recur contribution, so we are hiding the whole payment method selection field :
=> MAE-228: Prevent changing recur contribution payment method from/to Direct Debit

CRM/ManualDirectDebit/Batch/BatchHandler.php
Submitting Payment batches will result in recorded payments but with the payment method field empty : 
Submitting payment batches is resulting in having the correct payment method on the created payment, which `direct debit` : 
This PR is only part of the fix, the other part is that the Direct Debit payment method finincal account is not configured when Direct Debit extension is installed : 
So it need to be set to something too, For now we are not defaulting it to any specific value and will leave admins to configure it by themselves, but at some point we need  to find a suitable default.
=> MAE-261: Fix payment transaction payment method when submitting payments batches

CRM/ManualDirectDebit/Batch/Transaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
The contribution receive date filter inside the payments batch contributions search form, should be by default  set to "Choose date range"  where the start date (from date) is empty and the end date (to date) is set to today date, which is not the case currently. Not to mention that even changing the dates manually is not showing correct filtered results.
The receive date filter is set correctly to date range where the end date (to date) is today, and altering the dates is reflected on the results.
The issue is caused by this civicrm core PR : 
https://github.com/civicrm/civicrm-core/pull/14486
And since the contributions search form template in the DirectDebit extension  is using the one used in Core, and in the above PR the receive date filter fields names on the form get changed, which …
=> MAE-257: Fix payments batch contribution receive date search filter

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
The contributions search inside payment batch form show by default pending and cancelled contributions : 
but we need to change that so it only show the pending contributions.
Only pending contributions are showing :
=> MAE-268: Only show pending contributions in payments batch contributions search

CRM/ManualDirectDebit/Batch/Transaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
Users when search for contrbibutions in payment batch form need only to use the date filter, the time part is unimportant and we need to hide it :
=> MAE-269: Hide the time picker from the date range selector in payment batch search

CRM/ManualDirectDebit/Batch/Transaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
If the contribution receive date time part is not 12:00 AM, then it won't appear in the payment batch form as an available payment. 
The issue happen because when looking for available payments, the extensions compares the receive contribution  of the contribution which is a date + time, with the submitted time from the form which is getting converted to date only without the time part.
This is fixed by changing the query that fetch the available payments, so it also convert the receive date of the contribution to date only (without the time part) similar to the date submitted by the user to ensure that the comparison is happening correctly.
=> MAE-270: Fix receive date search filter if time is set

CRM/ManualDirectDebit/Batch/BatchHandler.php
When you are ready to submit a DD batch and you click the 'submit batch' button, you see the following:
Instructions Batch : 
Payments Batch : 
Here we updated the text to : 
Instructions Batch : 
Payments Batch :
=> MAE-254: Improving "submit batch" modal text

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Page/BatchList.php
There is no way for the user to update Direct Debit batches (instructions and payments batches). Also even after saving the batch, if the user tried to open the batch update page by going directly to the batch update URL from the browser or by trying to click the back button, the newly added stuff won't appear on the batch view page.
There is now a link to update the batch under the "Submit" button as can  be seen below, also the ability to assign new mandates or contributions to the batch is fixed.
The issue here with the mandate edit page originate from the way the extension stores mandates (or contributions in case of payment batch) assigned to the batch, when you create the batch for the first time and start assisting mandates to the batch, it will use ajax to store these mandates …
=> CGP-1474: Allow users to update Direct Debit batches

CRM/ManualDirectDebit/Mail/DataCollector/Base.php, templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentCollectionReminder.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentSignUpNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/Snippets/ActiveMemberships.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/Snippets/InstallmentList.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/Snippets/OrderSummary.tpl
Several fixes needed to be done on the DD e-mail templates:
1. Membership Amount shown on DD email notification is not included with VAT value. If you check the contribution amount & total amount, VAT is not included, while in some places of the email, VAT is included in the contribution amount.
2. Direct Debit Logo is missing on the email.
3. Spacing of the Direct Debit Guarantee block was too large.
4. Dates should be in CiviCRM short date format, as per configured settings on all the instances.
1. Tax was not taken into account when building the templates.
2. The URL for the logo was being built as a relative URL, but on the e-mail we need the absolute URL to be able to locate the image.
3. 60px were hard-coded as spacing before the guarantee block.
4. Dates were being shown in …
=> MAE-220: Fix Issues with DD E-mail Templates

CRM/ManualDirectDebit/Hook/BuildForm/Payment.php
We have multiple places in which users can change mandates, one of them is the one on the recurring contribution edit form, the issue with it in this form is that does not allow users to send a notification email to the contact about the mandate change, so we decided to disable the ability to change the mandate on the mentioned form instead of having to add and maintain the email sending feature. Users still have other places to change the mandate if they want to.
=> MAE-224: Prevent changing mandate from recur contribution edit form

CRM/ManualDirectDebit/Hook/BuildForm/Payment.php
1- Go to "Administer >> Payment Plan Settings" page and change the "Offline payment processor for back office" select field to "Live - Direct Debit" (you can also pick Test - Direct Debit).
2- Create a contact and add a membership to the contact with Payment Plan and Direct Debit payment method.
3- Complete any contribution (using record payment option), and choose "Direct Debit" as the payment method but leave the mandate field empty (pointing to the empty select option " - select -").
4- now try to delete any mandate or assigning new one to the recur contribution and it will fail showing a database error.
5- also if you "view" the completed contribution, the assigned mandate will be a hyphen instead of pointing to the actual mandate.
In general, it does not make sense to select a …
=> BASW-623: Fix attachment bewteen Contribution and mandate after recording a payment without selecting mandate

CRM/ManualDirectDebit/Upgrader.php, xml/customFields_install.xml
The activity types created by this extension are not reserved (by setting is_reserved field value to True) or hidden (by setting filter field value to True), this might allow users to delete these activities types by mistake as it happened with one of our clients.
The existing installation XML that creates these activities is updated to make sure they are both hidden and reserved, also a new upgrader is created to make sure that these activities are created with the mentioned filters if they are not already.
=> BASW-622: Hide and reserve DD activity types

CRM/ManualDirectDebit/Form/SignUp.php, manualdirectdebit.civix.php, templates/CRM/ManualDirectDebit/Form/SignUp.tpl, xml/Menu/manualdirectdebit.xml
This pull request is to add a direct debit sign up form to work stream branch. 
The form includes the functionality to load contribution details and check if
1. Contribution id parameter is passed to URL, if not redirect user to the home page.
2. Check if contribution is attached to recurring contribution, if not show error message. 
3. Check if contribution is status is pending, if not show error message. 
Direct debit sign up form did not exist on in Manual Direct Debit extension. 
The form is added to Manual Direct Debit Extensions. 
The form will throw below error message if contribution is not attached to recurring contribution. 
The form will throw below error message if contribution does not exist or status is not pending. 
Since the requirement is to make the form public and by …
=> RSE-1145: Create a direct debit sign up form

CRM/ManualDirectDebit/Form/SetUp.php, CRM/ManualDirectDebit/Form/SignUp.php, css/setUp.css, css/signUp.css, templates/CRM/ManualDirectDebit/Form/SetUp.tpl, templates/CRM/ManualDirectDebit/Form/SignUp.tpl, xml/Menu/manualdirectdebit.xml
This PR is to add information, input forms, direct debit text to the direct debit set up form. 
The form only showed the error message if invalid contribution_id parameter was passed.
The form that shows the payment date as a text. 
The form that shows payment dates as a drop-down list.
The majority of CSS classes used in the form was copied from CiviCRM public profile. 
There is also the custom css file that was created for fixing the issue of Bootstrap theme, so the label colour is displayed correctly. 
The custom CSS file also used for formatting the direct debit logo and submit the button layout. css
=> RSE-1146: Custom form fields

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/linters.yml, .github/workflows/tests.yml, bin/install-php-linter, phpcs-ruleset.xml, phpunit.xml.dist, tests/phpunit/BaseHeadlessTest.php, tests/phpunit/bootstrap.php
This PR is to add phpcs linter, PHP Unit Test suite and Github action workflows. 
Github Action workflows contain: 
- Linters workflow that run phpcs that check *.php when are added or/and updated.
- Unit Tests' workflow that run all php unit tests in the extension.
- The manual direct debit did not have functionality to run unit tests.
- unit tests were not run automatically. 
- phpcs linter was not run automatically. 
- GitHub actions was not implemented. 
- Linters action will be triggered when Pull Request is created and/or updated
- phpcs will only run if *.php is updated or added.
- Unit tests will to triggered and run every time PR is created and/or updated. 
- Linter and unit tests can be executed locally. 
PHP CS Linter is implemented based on Drupal code sniffer with some …
=> RSE-1143: Add phpunit, phpcs linter and GitHub action workflows

CRM/ManualDirectDebit/Form/SetUp.php, CRM/ManualDirectDebit/Page/Setup/Confirmation.php, css/setUp.css, templates/CRM/ManualDirectDebit/Form/SetUp.tpl, templates/CRM/ManualDirectDebit/Page/Setup/Confirmation.tpl, xml/Menu/manualdirectdebit.xml
This PR is to add functionalities to update, a recurring contribution record, selected contribution record, create a direct debit mandate and attach a created mandate to existing contribution record. 
The functionality does not exist. 
After the form is submitted: 
- Recurring Contribution payment method is updated to 'direct_debit'
- Cycle day is set to next payment run date from today's date. 
- Create a new  mandate 
- Attach a created mandate to existing recurring contribution and a selected contribution.
- Confirmation page is shown after the form is submitted.
=> RSE-1147:  Update recurring contribution

CRM/ManualDirectDebit/Form/SetUp.php
This PR is to create a new activity after the form is summited. 
The activity has never been created when the form is summited. 
_new_direct_debit_recurring_payment_ activity type is created after the form is submitted 
Activity source contact is assigned to a contact linked to the selected contribution as the form is a public form.
=> RSE-1174: Create a new direct debit recurring payment activity

CRM/ManualDirectDebit/Form/SetUp.php, CRM/ManualDirectDebit/Hook/Post/RecurContribution/Activity.php
This PR is to update the existing createActivity() function on the Direct Debit Setup form instead of creating a new function on a public form. 
A new function was created for creating an activity after the setup form is submitted. 
A new activity is created after assigning the mandate to a recurring contribution. 
When calling assignRecurringContributionMandate function, the new activity should be created automatically. However, the activity was not created before source_id was empty as the data was submitted from a public form. 
This PR updates the createActivity() functions to check if $loggedContactId is existed. If not, the contribution contact id will be used instead.
=> RSE-1147: Create a new activity after the form is submited.

info.xml
This release include the following fixes and changes : 
- BASW-623: Fix attachment bewteen Contribution and mandate after recording a payment without selecting mandate (https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/162)
- BASW-622 : Hide and reserve DD activity types (https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/163)
=> MAE-327: 2.2.0 release

CRM/ManualDirectDebit/Form/SetUp.php
This PR adds additional required fields when saving a mandate.
dd_ref, authorisation_date and originator_number were not assigned to mandate values when saving a mandate 
dd_ref, authorisation_date and originator_number will be saved to a mandate. 
- dd_ref - dd ref is a required field and cannot be empty, so we need to pass a value 'DD Ref' to ensure that the actal DD ref will be generated. 
See:https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blame/master/CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php#L71
and https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/100
- originator_number - Originator number is a required field and does not have default value as it will be set differently depends on organizations setup their direct debit and …
=> RSE-1147: Save mandate

CRM/ManualDirectDebit/Form/SetUp.php
This PR adds weight param when getting Originator Number to ensure that we get the first value from originator number list by weight instead of ID. 
The originator number was getting from the first value based on ID.
The originator number  first value will be getting from the weight = 1 rather than value id.
=> RSE-1147: Add weight in the parameter for getting Originator number

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php
This PR is to fix issues when error when navigate to create or edit Membership when manual direct debit  and Sagpay  (Omnipay version)  extensions are installed together. 
This PR also fixes the code format error threw by phpcs. 
Sagepay (Omnipay version) installs an option group called Payment Type (payment_type) that comes with option values and one of them are direct_debit.  The direct_debit name are duplicated with option_value name in payment_insturement  group.
To ensure that Manual Direct Debit extension will get the correct  direct_debit value that belongs to payment_instruement group. 
So we will pass payment_instrument option group parameter when calling OptionValue API.
```
civicrm_api3('OptionValue', 'getvalue', [
'return' => "value",
'name' => "direct_debit", …
```
=> MAE-355: Sagepay integration issue

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php
This PR is to fix issues when error when navigate to create or edit Membership when manual direct debit  and Sagpay  (Omnipay version)  extensions are installed together. 
This PR also fixes the code format error threw by phpcs. 
Sagepay (Omnipay version) installs an option group called Payment Type (payment_type) that comes with option values and one of them are direct_debit.  The direct_debit name are duplicated with option_value name in payment_insturement  group.
To ensure that Manual Direct Debit extension will get the correct  direct_debit value that belongs to payment_instruement group. 
So we will pass payment_instrument option group parameter when calling OptionValue API.
```
civicrm_api3('OptionValue', 'getvalue', [
'return' => "value",
'name' => "direct_debit", …
```
=> MAE-335: Sagepay integration issue

CRM/ManualDirectDebit/Form/SetUp.php
This PR is to fix the issue when payment method has not been updated to 'direct debit' when the form is submitted'  
Contribution payment method was not updated. 
Contribution payment method will be updated to 'direct debit'.
=> RSE-1230: Update contribution payment method to direct debit

CRM/ManualDirectDebit/Form/SetUp.php
This PRs to hide VAT field if no VAT is configured on the membership type.
VAT is displayed with £0.00 if no VAT is configured on the membership type.
VAT will not display if no VAT is configured on the membership type.
=> RSE-1128: Hide tax amount

CRM/ManualDirectDebit/Mail/DataCollector/Base.php, CRM/ManualDirectDebit/Mail/Notification.php, CRM/ManualDirectDebit/Mail/Task/ContributionEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/MailDetailsModel.php, CRM/ManualDirectDebit/ScheduleJob/Reminder.php
For each contribution satisfying conditions for the scheduled job "Send Direct Debit Payment Collection Reminders" an e-mail with the "Direct Debit Payment Collection Reminder" message template should get sent. These conditions are:
- Payment Method is Direct Debit
- Contribution Status is Pending or Cancelled
- Receipt Date is empty
- "Received Date" minus "Days in advance for Collection Reminder" is equal to or smaller than today
However, running the job on SPAB results in failure, logged on the job's execution job:
> Job is failed with'Failure, Error message: One of parameters  (value: ) is not of the type Integer'
No DD payment collection reminder emails are triggered.
No Activities are created.
If an exception was thrown amidst the sending of reminders for direct debit collections, …
=> SPAB-976: Implement Handling of Exceptions on Collection Reminder Job

CRM/ManualDirectDebit/Form/SetUp.php, templates/CRM/ManualDirectDebit/Form/SetUp.tpl
This PR is to update the behaviour  of setting contribution recurring cycle day when sign up with Direct Debit on public form.
The public Direct Debit sign up form allows the end user to select the payment date from payment collection run date. 
The option to select payment run date is removed and the Recurring Contribution cycle day will be calculated automatically based on the Manual Direct debit configuration and the sign up date. 
The calculation of contribution Recurring Cycle day will only be calculated if the frequency is yearly and will be calculated base on. 
1. The payment collection run date.
2. The minimum days to first payment. 
3. The sign up date. 
For example, 
if the payment run date is set on 7th and 21st and the minimum days to first payment is set to 5 days.
Scenario …
=> RSE-1129: Set Contribution Recurring cycle day automatically

CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Upgrader.php, xml/customFields_install.xml
When clicking on the "Create New Cancellation Batch" Item on the DD menu, we need to show a form similar to the other batch creation forms where:
- Title: Create Cancelled Instructions Batch
- Batch ID: Incremental numbering - not editable.
- Batch name Defaults to: Cancelled Instruction Batch - "Batch ID" - required
- Batch Type: Cancelled Instruction Batch
- Originator number
- Select list of Originator number - required
The form did not exist, and clicking the menu item showed a 404.
Clicking on the menu item now shows the form. If the form is saved, the batch is created and the user is forwarded to the batch update view.
=> IO-75: Enable Form to Create Cancellation Batches

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Hook/Links/LinkProvider.php, CRM/ManualDirectDebit/Page/AJAX.php, CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchSubmissionQueue.php, CRM/ManualDirectDebit/Page/BatchTransaction.php, CRM/ManualDirectDebit/Upgrader.php
The form that shows available mandates to be cancelled in a batch should mee these criteria:
- Title: Cancelled Instructions
- The screen should filter to only show mandates with status code = 0C.
- Mandates should be excluded if they have been including in any other "Cancelled Instruction" batch unless that batch has been "discarded".
When showing the form to manage mandates in batch, all mandates were shown. 
Only mandates with dd_code = 0C are shown. Also implemented some class constants to hold the batch type's machine name, to have a single source of truth, and refactored the code to used those class constants throughout batch management logic.
=> IO-76: Implement Cancellation Batch Management Form

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/MandateContributionConnector.php, CRM/ManualDirectDebit/Test/Fabricator/Contribution.php, tests/phpunit/CRM/ManualDirectDebit/Common/MandateStorageManagerTest.php
This PR mainly fixes the issue when updating mandate for contribution. 
The PR also fixes bad code reported by linter. 
Mandate id that links to contribution is liking via CiviCRM custom field and the mandate is stored in varchar by default so when the mandate id is passed to SQL and the mandate id was not casting to string. 
```
$query = "UPDATE `civicrm_value_dd_information` AS dd_information);
LEFT JOIN `civicrm_contribution` AS contribution ON dd_information.entity_id = contribution.id 	
SET dd_information.mandate_id = $mandateId 	 
WHERE dd_information.mandate_id = $oldMandateId 	           
AND contribution.contribution_status_id != $completedStatusId";
```
The error occurred.  This issue happens with MYSQL database that has STRICT_TRANS_TABLES, mode on 
The code has been updated to …
=> SPAB-1045: Fix new mandate

info.xml
This PR is to bump version 3.0.0 for Manual Direct Debit extension for ME v3 release.
=> MAE-385: Bump version to 3.0.0

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchTableListHandler.php, CRM/ManualDirectDebit/Upgrader.php, templates/CRM/ManualDirectDebit/Page/BatchList.tpl
After creating a cancellation batch, we need to be able to add/remove instructions from the batch and save, export or discard it. Furthermore, we need to be able to view the list of batches, and use a search form to find the batch we need by type and created date.
- Although it was possible to add instructions to a cancellation batch, exporting it would always result in an empty CSV.
- After saving a batch, system redirected user to list of batches, where all batches not related to payments would be shown. There was no way to filter list of batches to find the one user needs.
- Exporting was fixed so CSV is now populated with instructions added to cancellations batch.
- View that displays list of batches now has a filter to search byt batch type and by created date, allowing user to …
=> IO-83: Implement Cancellation Batch Management

CRM/ManualDirectDebit/Common/MandateStorageManager.php, tests/phpunit/CRM/ManualDirectDebit/Common/MandateStorageManagerTest.php
This PR is to fix error when delete mandate similar to PR https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/192 
This issue happens with MYSQL database that has STRICT_TRANS_TABLES, mode on 
The parameter mandate id that was passing to query was Integer.
The parameter mandate id that is now passing to query as String.
Mandate id that links to contribution is liking via CiviCRM custom field and the mandate is stored as varchar  so when the mandate id is passed to SQL as  integer, MySQL that has STRICT_TRANS_TABLES mode on will throw the error.
=> SPAB-1045: Fix Delete mandate

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/Custom/CancellationBatchChecker.php, CRM/ManualDirectDebit/Page/BatchSubmissionQueue.php, manualdirectdebit.php
We need to add the following validations to manage Direct Debit batches with 0C status:
- Remove Mandates for Cancelled mandates batches if their status changes from 0C: If the status of a mandate is changed from 0C to another status, and that mandate was previously in a draft batch (a batch which has been saved but is not submitted) then it should be removed immediately from that batch. Mandates which are in a submitted batch and subsequently have their status changed should not be removed from the batch.
- If I have a draft batch (saved but not submitted) then when I submit the batch the system should validate that all of the mandates have a status of 0C. If any do not then show an error message: 
> The batch contains the following mandates that no longer has the status of 0C:
> - List …
=> IO-87: Implement Validation of Cancellation Batch Submission

CRM/ManualDirectDebit/Batch/Transaction.php
When you create a payment batch and click the View button on one of the listed contributions, it should navigate to the contact's contribution page and open the exact contribution in a popup. However it just opens a popup on the batch page and shows the contribution.
Clicking the view action on a line of the manage payment batch screen opened a popup with the infromation for the contribution related to the payment in the batch.
View action now takes the user to the contact's detail view, preloads the Contribution tab, and opens the specific contribution in a popup.
I found a JS script added some time ago that already altered the Contact's detail view, so that if a parameter is passed in the url, the JS is added and the contribution ID used to open it in a popup.
See: …
=> CGP-1480: Open Contact and Contribution From Payment Batch View

CRM/ManualDirectDebit/Form/Batch.php
Cancel button on batch creation forms (eg. Direct Debit > Create New Instructions Batch), doesn't work.
Clicking the cancel button on a batch creation form just refreshed the page.
https://drive.google.com/file/d/12GBwp_SU1FxnKjq9koMLF_9sZY3p0mcV/view
Clicking the cancel button redirects user to civicrm home.
=> MAE-264: Implement Cancel Button on Batch Creation Pages

CRM/ManualDirectDebit/Hook/QueryObjects/Contribution.php, manualdirectdebit.php
'Find Contributions' by 'Batch Name' filter is not returning any records  though we have open DD batch records.
Filtering of contributions by batch records expected the financial transaction associated with the contribution  (civicrm_financial_trxn), to be the entity referenced in the batch. Thus the JOIN clause looked something like:
```sql
LEFT JOIN civicrm_entity_batch ON ( 
civicrm_entity_batch.entity_table = 'civicrm_financial_trxn'
AND civicrm_financial_trxn.id = civicrm_entity_batch.entity_id 
) 
LEFT JOIN civicrm_batch ON civicrm_entity_batch.batch_id = civicrm_batch.id
```
This was then followed by a WHERE clause like:
```sql
...
AND (
civicrm_entity_batch.batch_id = '13'
AND civicrm_contribution.id != 0
)
```
Implemented hook_civicrm_queryObjects hook to add a class that alters …
=> MAE-225: Fix Contribution Search by Batch for Payment Batches

CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Page/BatchTransaction.php
Batch number is included in the title - "Cancelled Instructions Batch - 15". As per Specification/ticket, it should be "Cancelled Instructions".
Mandate once processed in  Instruction batch, is not displayed again in Cancelled instruction batch though the status is updated to 'OC'.
Query to obtain list of available mandates was checking if the mandate was in any other batch that was not discarded. This meant if a batch was in a submitted new instructions batch, it would never appear on a cancellations batch.
Added a condition to the query to obtain mandates so that the check is only done on batches of the same type.
=> IO-110: Fix List of Available Mandates When Tied to Other Batch Types

CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchTransaction.php
Issues were found when testing screen to manage batches:
1. Filter - Batch type - select list: Can we just show only Instruction batch & Cancelled Instruction batch types 
in this screen?  I think we should not show all the batch types in this screen.   https://nimb.ws/yzRY8V
2. -  Date range : 'To' Date filter is not working when used. IO-111:  Manage Instruction Batches- Date range : 'To' Date filter is not working when used.DEVELOPMENT IN PROGRESS is created separately to track
3. -  Instruction Count is always 0 in the DD Instruction View Batch screen  IO-112:  Instruction Count is always 0 in the DD Instruction View Batch screen READY FOR DEVELOPMENT is created to track
1. All batch types were baing showed on search field.
2. Value of to field was being used to filter any mandates …
=> IO-84: Fixes and Improvements

CRM/ManualDirectDebit/Page/BatchList.php, templates/CRM/ManualDirectDebit/Page/BatchList.tpl
After submitting Cancelled Instruction batch, a confirmation message popup is displayed as below, 
https://nimb.ws/rPpXij
We need to modify the above message and match with existing Payment batch & Instruction batch confirmation messages, when done from the detailed view of the batch.
Cancelled Instruction batch - New message
"Submit Batch  
"You are submitting all items within this batch:
Please note that this process is not reversible."
New DD Instruction batch 
"You are submitting all items within this batch:
- All mandates in the batch that currently have instruction code 0N will be transitioned to instruction code 01
- The status of this batch will be updated to 'Submitted'. Please note that this process is not reversible."
DD Payment batch
"You are submitting all items within this …
=> IO-84: Change Sumbission Message per Batch Type

CRM/ManualDirectDebit/Batch/BatchHandler.php
After submitting Cancelled Instruction batch, a confirmation message popup is displayed as below,
**Cancelled Instruction batch - Current behavior** 
https://nimb.ws/rPpXij
"Are you sure you want to submit this batch?
Please note that this process is not reversible."
**Cancelled Instruction batch - New message**
We need to modify the above message and match with existing Payment batch & Instruction batch confirmation message.
"You are submitting all items within this batch:
Please note that this process is not reversible."
Default message used for cacnellations submit was 
> Are you sure you want to submit this batch?
> Please note that this process is not reversible."
Updated message to:
> You are submitting all items within this batch:
> 
> Please note that this process is not …
=> IO-114: Fix Warning Message When Submitting Cancellations Batch

css/batchSearch.css, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Page/BatchList.tpl
A search form has been added to the Manage Instruction Batches list view to be able to filter by batch type and creation date. This was done in this PR:
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/195
Jamie has asked us to improve the styling of the form.
**Wireframe**
The form required better styling.
Form was styled according to provided wireframe.
=> IO-101: Improve Batch Search Form Styling

CRM/ManualDirectDebit/Batch/Transaction.php
Mandates/Payments should be excluded if they have been including in any other batch unless that batch has been "discarded".
This is not working now in Instruction batch, cancelled instruction batch or payment batch screens  after IO-113: Unify Batch Management in Single Screen fix. 
Mandates/Payments  are still available in the main batch screen even if they have been included in other batch.
A mistake was made on the query to exclude mandates in other batches.
Fixed the query.
=> IO-115: Exclude Mandates From List if Added to Other Batch of Same Type

CRM/ManualDirectDebit/Page/BatchList.php
After selecting the menu option "Manage Direct Batches",
1. Heading should be "Manage Direct Batches" instead of "Manage Instruction Batches"
2. Column name should be changed from Instruction count / to only ‘count’  
Heading and column name have been changed according to Batch Type selection. When "New Direct Debit Instruction / Cancelled Instructions" batch type is selected - Heading got changed to "Manage Instruction Batches" and Column name to 'Instruction Count". When "Direct Debit Payments" batch type is selected - Heading got changed to "View Payment Batches" and Column name to 'Payment Count".
Default values for page title and count column table header were those for instructions.
Added generic default values, for when no batch type is selected.
=> IO-113: Fix Dynamic Page Title and Table Headers

CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Hook/PageRun/ViewCustomData.php, js/mandateEdit.js, manualdirectdebit.php, templates/CRM/Contact/Page/View/CustomDataEditButtons.tpl
If a contact had several mandates, clicking the "View" action from the batch management screen opened a popup that showed all mandates for the contact, instead of just the one that was clicked on. 
The URL used for the action corresponded to the one used by CiviCRM to show the list of custom field group records associated to a contact.
https://drive.google.com/file/d/1asTI8AVDCLVke2etzAPZp8Krq2CI7YQx/view
The URL of the action was replaced with the one useed in CiviCRM to display a specific record of a custom group.
=> MAE-252: Show Only One Mandate When Clicking View on Batch Management Screen

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Hook/Custom/CancellationBatchChecker.php, CRM/ManualDirectDebit/Hook/Links/LinkProvider.php, CRM/ManualDirectDebit/Page/AJAX.php, CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchSubmissionQueue.php, CRM/ManualDirectDebit/Page/BatchTableListHandler.php, CRM/ManualDirectDebit/Page/BatchTransaction.php, CRM/ManualDirectDebit/Upgrader.php, css/batchSearch.css, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Page/BatchList.tpl, xml/customFields_install.xml
We need to provide functionality such that a user can export mandates that have been cancelled, so that they can import them into their direct debit software and process the cancellations.
**User Story** 
As a CiviCRM user. I would like to be able to create a mandate batch which includes cancelled direct debit mandates. So that I can import them into my Direct Debit management software to have the mandates cancelled.
No functionality to manage direct debit cancellations existed, save for the possibility to change the status of a mandate to '0C' (Cancelled).
Functionality to create, manage and export cancellations is implemented. This comprises the PR's done for:
- IO-74: #189
- IO-75: #190
- IO-76: #191
- IO-77: #204, #205
- IO-83: #195
- IO-87: #198
- IO-101: #208
- IO-113: #206, #210
- …
=> IO-54: Managing Cancelled Mandates

CRM/ManualDirectDebit/Upgrader.php
This PR is to change the location of Direct Debit Batch menu from main menu to locate under Contribution menu
The menu was not used navigation hook to create a menu. The menu is installed directly to the database during the extension installation. Since we do not need to move the menu for existing installation, the upgrader is not required and the change is made on the installation step.
=> MAE-404: Menu changes

.github/workflows/tests.yml, info.xml
Bumping version to 4.0.0 as part of Membershipextras suite version 4.0.0 release.
Also as part of this PR I've updated the tests workflow file to use Civicrm and drupal versions specified in Compuclient
=> MAE-411: Bump version to 4.0.0

CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php, manualdirectdebit.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContributionTest.php, tests/phpunit/bootstrap.php
We need to calculate first instalment receive date in such a way that:
- Takes membership start date
- Finds the next NIRD (New instruction run date) and adds MDFNI (Min days for New instruction to First payment) 
- Finds the next payment collection run date available after the padded next instruction run date.
Thus, first instalment receive date should be first available payment collection run date after the the first padded instruction run date, which in turn should be after the membership start date.
There was no way to change the first instalment's receive date.
Implemented the membership extras calculateContributionReceiveDate hook to change the first instalment's receive date.
Hook is dispatched from membership extras extension, implemented in this PR: …
=> IO-123: Implement calculateContributionReceiveDate Hook

CRM/ManualDirectDebit/Common/SettingsManager.php, settings/ManualDirectDebit.setting.php
We need a setting so that users can choose when the second instalment should be for, under specific scenarios. The setting should be named"Second Instalment Date Behaviour", a dropdown with the following options:
- Take second instalment 1 month after the first instalment (Default)
- Take second instalment in the second month of membership
The setting did not exist.
Added the setting to the payment options block of DD settings form.
=> IO-125: Add Setting to Alter Behaviour of Second Instalment

CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContributionTest.php
First installment is calculated incorrectly and it seems like it does not consider the 2nd value mentioned in "Payment collection run dates" DD configuration for the calculation. 
Consider this example - When the new instruction Run Date and minimum number of days (combined) is after the cycle date the first instalment should be scheduled for the following month. But it is not.
1. Update the DD configurations as below,
1. New instruction run dates - 4
1. Payment collection run dates  -5, 21	
1. Minimum days from new instruction to first payment - 3
2. Create a membership effective from today 18-Dec-2020 with the same payment plan start date
3. Membership is created effective from today . 
4. But 1st installment is displayed as 5th Jan 2021 . It should be 21st Jan 2021 
Calculation -  4th …
=> IO-131: Fix Failing Scenarios on First Receive Date Calculation

CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/Base.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/ContributionBase.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, manualdirectdebit.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php
Using the "Second Instalment Date Behaviour" setting, we need to implement the logic for each option:
- Take second instalment 1 month after the first instalment (Default): Here, the date of the second instalment is relative to the date of the first instalment. If the first instalment is delayed due to the fact that the first instalment payment run date in the first month was missed, the second instalment will be 1 month from that date. All following instalments will be 1 month following the previous. This might be preferable for ensuring that members do not have to pay for multiple instalments in the same month, but it may mean that the final instalment for a membership is taken in the month after the membership has expired, which might be undesirable from your organisations perspective. …
=> IO-126: Alter Receive Date of Other Instalments Based on DD Settings

CRM/ManualDirectDebit/Form/Configurations.php, settings/ManualDirectDebit.setting.php, templates/CRM/ManualDirectDebit/Form/Configurations.hlp, templates/CRM/ManualDirectDebit/Form/Configurations.tpl
Issues were found on the DD configurations form:
1. Sub heading "Instalment Config' which is given in the ticket screenshot is missing. New setting is displayed under the existing "Payment config' sub heading.
2. Help icon for the new setting is missing. Hence unable to validate the help text given in the ticket description
3. Should we update capitalization for sub headings on the screen? 
4. Drop down option default value should be  "Take second instalment 1 month after the first instalment" , but it is not set and the value is blank at first 
1. Heading was missing.
2. Help texts were missing for the new setting.
3. Titles of each group were not properly capitalized.
4. Default values were not being taken into account on the whole form. 
1. Added new Instalment Config group with the …
=> IO-125: Fix Issues With Settings Form

CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php
Second instalment date is before the 1st instalment date for the below scenario.
DD Settings: 
- New instruction run dates: 4
- Payment collection run dates: 5
- Minimum days from new instruction to first payment: 3
- Second Instalment Date Behavior: Option 2 ( Take 2nd instalment in 2nd month of membership)
Scenario:
1. Create a membership effective from 04-Aug-2020 of 12 instalments 
2. 1st instalment is - 5-Oct -2020 (Calculation - 4t Sep 2020 is the next instruction date + 3 days which is 7th Sep 2020. So the next payment collection run date is 5th Oct 2020).
3. Here 2nd instalment is before 1st instalment. 2nd instalment: 5-Sep 2020. 
4. 3rd instalment is 05 Oct 2020
Under some configurations, if setting to force the second instalment on the second month is enabled, it can happen …
=> IO-134: Fix Scenario Where First Instalment is After Second

settings/ManualDirectDebit.setting.php
Run dates above the 28th (ie. 29th, 30th and 31st) should not be allowed to be chosen as payment collection run dates.
Values shown on the DD configuration form for the payment collection run dates showed values from 1 up to the 31st.
Altered the setting's definition so only values up to the 28th are available on the select field of the form.
=> IO-129: Do not Allow Payment Run Dates Above the 28th

info.xml
Bumping version to 4.1.0 as part of Membershipextras suite version 4.1.0 release.
=> MAE-457: Bump version to 4.1.0

CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Form/Configurations.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/Base.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/ContributionBase.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, manualdirectdebit.php, settings/ManualDirectDebit.setting.php, templates/CRM/ManualDirectDebit/Form/Configurations.hlp, templates/CRM/ManualDirectDebit/Form/Configurations.tpl, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php, tests/phpunit/bootstrap.php
We need to improve the Direct Debit Start Date. The Start date of the DD payment plan should occur in the same month of sign up when possible. When it is not possible, the second and first instalment should be taken in the same month to match the membership and payments duration, though this should be an optional setting.
The is a final release into master of the work done for:
- IO-123: Calculate First Instalment Date
- IO-124: Calculate Cycle Date
- IO-125: Add New Setting
- IO-126: Calculate Second Instalment Date Using New Setting
- IO-129: Add Validation to Payment Run Dates
- IO-132: Autorenewal Job is Failing
- IO-135: Issue wit Second Instalment
Functionality to calculate first and second instalment dates according to new instruction and payment run dates was not implemented.
1. …
=> IO-56: Improve Direct Debit payment plan date calculations

templates/CRM/ManualDirectDebit/Page/BatchList.tpl
As part of updating the button markup for [supporting 5.35 on shoreditch](https://github.com/civicrm/org.civicrm.shoreditch/commit/e7986e2327b69d50e57717bc306f9906491a17ff), the search button styles got broken as it is having old classes and markup. This PR fixes the markup for the search button to retain its styles.
* The idea was to change `input.crm-form-submit` to `button.crm-form-submit` HTML markup and the `<i>` (icon HTML) was added inside of it.
=> MAE-493: Fix search button markup on manage screen

CRM/ManualDirectDebit/Form/Email/Contribution.php, CRM/ManualDirectDebit/Form/Email/Membership.php, CRM/ManualDirectDebit/Mail/Task/Email/AbstractEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/Email/ContributionEmail.php, CRM/ManualDirectDebit/Mail/Task/Email/MembershipEmail.php, CRM/ManualDirectDebit/Mail/Task/Mail.php
When using Find contributions / Find memberships to search for contribution or memberships, Manual Direct Debit extensions provide a feature to send direct debit notifications on the actions using Manual Direct Templates. 
The implementation was extended CiviCRM core functions which were moved from the class to traits since CiviCRM 5.34 [here](https://github.com/civicrm/civicrm-core/pull/19214). 
This PR refactors the code in the Manual Direct Debit to align with the changes in the CiviCRM core. 
Error was present when sending email from "Send Direct Debit Notifications" actions when using Direct Debit templates or CiviCRM templates.
Email can be sent when using Send Direct Debit Notifications when using either
- Direct Debit templates.
- CiviCRM templates. 
This PR also takes an …
=> MAE-501: Fix unable to send direct debit notifications.

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Queue/Task/BatchSubmission/PaymentItem.php
Fixing payment batch submission after CiviCRM 5.35 upgrade
Manual direct debit is using the core method "transitionComponentWithReturnMessage" that is in the Contribution BAO class, though this method is now removed in CiviCRM core (see https://github.com/civicrm/civicrm-core/pull/18961 for more info), and thus it results in failure when submitting the payment batch.
Here I replaced the calls for this method with "transitionComponents" method, given that the former is basically calling it but just with returning some extra feedback messages, and that these feedback messages are not even used or showed back to the user in this extension, so it is safe to just call "transitionComponents" instead.
=> MAE-494: Fix payment batch submission after CiviCRM 5.35 upgrade

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Form/Email/Contribution.php, CRM/ManualDirectDebit/Form/Email/Membership.php, CRM/ManualDirectDebit/Mail/Task/Email/AbstractEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/Email/ContributionEmail.php, CRM/ManualDirectDebit/Mail/Task/Email/MembershipEmail.php, CRM/ManualDirectDebit/Mail/Task/Mail.php, CRM/ManualDirectDebit/Queue/Task/BatchSubmission/PaymentItem.php, templates/CRM/ManualDirectDebit/Page/BatchList.tpl
Merging the fixes we did for CiviCRM 5.35 which includes :
MAE-493: https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/232
MAE-494: https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/230
MAE-501: https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/231
=> MAE-483: Merging workstream branch for CiviCRM 5.35 fixes to master branch

manualdirectdebit.php, xml/Menu/manualdirectdebit.xml
Currently, the direct debit configuration can only be accessed with a user that has permission `administer CiviCRM`. In some systems like SaaS platform or even in some organisations, that may not want to give  `administer CiviCRM` to the site administer  but allows access to the certain admin pages and forms.   
This PR adds new `administer Manual Direct Debit` permission and assign this permission to existing configuration pages that  allows a system admin to assign a new permission to other roles, so the user with the role can access the setting pages without having a global `administer CiviCRM` permission.
Only user that has `administer CiviCRM` permission can access Manual Direct Debit configuration form. 
Either user that has `administer CiviCRM`  or  `administer Manual Direct Debit` …
=> CIVIPLUS-176: Add administer Manual Direct Debit permission

CRM/ManualDirectDebit/Batch/Transaction.php
This PR fixes the slow loading of "Manage Direct Debit Batches" page.
Opening the "Manage Direct Debit Batches" page will **take a lot of time and maybe "Timeout" error** if the table `civicrm_value_dd_information` has so many records (> 100k).
Opening the "Manage Direct Debit Batches" page will **be fast** even if the table `civicrm_value_dd_information` has so many records (> 100k).
The `getBatchRows` method uses the same query base to search for direct debit payments and instruction batch.
The query will be so slow if the table `civicrm_value_dd_information` has so many records (> 100k) because the MYSQL will load the whole civicrm_value_dd_information to the memory instead of using the indexes.
```sql
EXPLAIN SELECT * FROM civicrm_value_dd_mandate LEFT JOIN …
```
=> BASW-774: Fix the slow loading of "Manage Direct Debit Batches" page

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php
This PR fixes the error when exporting the batches. The regression was introduced by the previous https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/240 PR.
Clicking on the export button will show error page.
Clicking on the export button will start downloading the batch.
As you can see from the following error message , the method `getDDMandateInstructions` is not defined anymore.
```php
array(6) {
["%type"]=>
string(5) "Error"
["!message"]=>
string(93) "Call to undefined method CRM_ManualDirectDebit_Batch_Transaction::getDDMandateInstructions()"
["%function"]=>
string(66) "CRM_ManualDirectDebit_Batch_BatchHandler->getMandateCurrentState()"
["%file"]=>
string(158) "CRM/ManualDirectDebit/Batch/BatchHandler.php"
["%line"]=>
int(381)
["severity_level"]=>
int(3)
}
```
This …
=> BASW-774: Fix regression when exporting batches

CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Form/Configurations.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/Base.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, manualdirectdebit.php, settings/ManualDirectDebit.setting.php, templates/CRM/ManualDirectDebit/Form/Configurations.hlp, templates/CRM/ManualDirectDebit/Form/Configurations.tpl, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php, tests/phpunit/bootstrap.php
This PR reverts the reverted PR https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/pull/229 so the changes on for IO-56-workstream-improve-dd-start-date that were already applied then were reverted on master branch can be merged back to master branch again. 
This PR merges to a newly created branch, IO-56-workstream branch, which was branched off master branch as of today. The reason that I created a new workstream branch instead of reverting the reverted branch back to the master branch as IO-56 are not completed yet, and we would need this branch for QA before we merge the workstream branch to master branch as well as using this branch will use for merging adding new changes from[IO-136 ](https://compucorp.atlassian.net/browse/IO-136). 
Test failings because the changes that …
=> IO-177: Revert "Revert "IO-56: Improve Direct Debit payment plan date calculations""

.github/workflows/tests.yml, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/Base.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContribution.php, CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, CRM/ManualDirectDebit/Test/Helper/PaymentPlanTrait.php, manualdirectdebit.php, settings/ManualDirectDebit.setting.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContributionTest.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php
This PR depends on this [PR](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/380)
This PR updates the logic that the calculation contribution received date as the hook parameters has been changed from contribution array object to a new set of parameters.
CalculateContribuitonRecieveDate was implemented based on the contribution object.
CalculateContribuitonRecieveDate implementation is implemented as per new parameters passing from the hook. 
The new parameters are: 
```
$params = [
'membership_id' => NULL,
'contribution_recur_id' => NULL,
'previous_instalment_date' => NULL,
'payment_schedule' => $this->schedule,
'payment_instrument_id' => $paymentMethod,
'membership_start_date' => $firstInstalmentDate,
'frequency_interval' => $instalmentFrequencyInterval, …
```
=> IO-136: V5 contribution receive date calculation

CRM/ManualDirectDebit/Common/MandateStorageManager.php
This PR fixes the issue that the mandate ID is not assigned to all contributions when creating a new membership with fixed membership type and using direct debit as payment method.
When sign up with fixed membership type and membership amount is pro-rated, the mandate will ONLY assign to recurring contribution and first contribution.
When sign up with fixed membership type and membership amount is pro-rated, the mandate will ONLY assign to recurring contribution and all contributions.
This PR removes a function that checks if number of contributions equals to recurring contribution's instalments number. As number of instalment of recurring contributions and number of contributions will not always equal to recurring contribution's instalments, if the membership amount is pro-rated
=> IO-152: Remove checking no of instalments

CRM/ManualDirectDebit/Hook/PageRun/ViewCustomData.php, templates/CRM/Contact/Page/View/CustomDataEditButtons.tpl
Trying to edit a mandate inside the instructions batch page shows and empty page.
Trying to edit a mandate inside the instructions batch page shows the mandate edit form correctly.
The template was hardcoded to use the group id = 10 in the edit URL which is not necessarily the mandate custom group id on all sites, so I changed it to be set dynamically.
=> MAE-495: Fix mandate edit link in batch screen

.github/workflows/tests.yml, CRM/ManualDirectDebit/Hook/Custom/Contribution/ContributionDataGenerator.php
The class **CRM_MembershipExtras_Service_InstallmentReceiveDateCalculator** was renamed to **CRM_MembershipExtras_Service_InstalmentReceiveDateCalculator** in v5 (which was done as an effort to fix the typo
in the word installment across our Membershipextra extensions) but the reference for it here was not updated,  which resulted in fatal error when trying to submit webforms that have payment plans configured with direct debit. This PR fixes that.
=> MAE-545: Fix Direct debit payment plan webform submissions

CRM/ManualDirectDebit/Hook/Custom/Contribution/ContributionDataGenerator.php
The code is no longer needed since in this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/389
we stop allowing API and DAO calls from updating  'Next contribution date' field value, so rendering all this code useless.
In later PRs I  introduce different way to calculate the value of this field
=> MAE-581: Stop updating 'Next contribution date' field

.github/workflows/tests.yml
Update CiviCRM version in tests workflow to match the CiviCRM version on Compuclient 1.29
=> COMCL-169: Update CiviCRM version in tests workflow

CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/OtherContributionTest.php
In this PR we ensure that Hook_CalculateContributionReceiveDate_OtherContribution class only runs when the payment method is direct debit and the contribution is for a new membership. 
Hook_CalculateContributionReceiveDate_OtherContribution is processed and the contribution date for the 3rd instalment onward uses the date from the 2nd instalment date as its base, even though this is an intended logic for direct debit contributions only.
Hook_CalculateContributionReceiveDate_OtherContribution is not processed since the payment method is not direct debit, therefore, the contribution for the 3rd instalment and above uses the date from the 1st instalment as its base.
=> MAE-733: Fix condition for processing Hook_CalculateContributionReceiveDate_OtherContribution

info.xml, manualdirectdebit.civix.php, manualdirectdebit.php, mixin/menu-xml@1.0.0.mixin.php, mixin/polyfill.php, mixin/setting-php@1.0.0.mixin.php, phpunit.xml.dist, settings/ManualDirectDebit.setting.php, tests/phpunit/BaseHeadlessTest.php
This extension `civix` file is incompatible with `PHP 8.0`, to resolve the compatibility issue we regenerated the `civix` files using the command `civix upgrade`.
As part of this upgrade process, the following changes were introduced also:
1. PHPUnit_Framework_TestCase namespace is changed to PHPUnit\Framework\TestCase
2. Empty hook functions are removed.
3. Some hook functions will be converted to mixins to ease code reusability, below is a copy of the prompt displayed during the upgrade process, implying that if any of the mentioned hooks are used in the extension it will be moved to a standalone file in the `mixins` folder.
```
! [NOTE] Civix v22.05 converts several functions to mixins. This reduces code-duplication  
!        and will enable easier updates in the future. …
```
=> MAE-847: Regenerate civix module files for PHP8

.github/workflows/tests.yml, CRM/ManualDirectDebit/Hook/MandateContributionConnector.php, CRM/ManualDirectDebit/Hook/QueryObjects/Contribution.php, tests/phpunit/CRM/ManualDirectDebit/Common/MandateStorageManagerTest.php
As part of our plan to move to PHP 8.0, we are updating the unit-tests container to use the PHP 8 version of it. With this PHP update, we are also updating Drupal to version 7.79 and CiviCRM to version 5.51.3.
Updating the container and the CiviCRM version, resulted in the following errors:
1- 
```
E..PHP Fatal error:  Cannot make static method CRM_Contact_BAO_Query_Interface::from() non static in class CRM_ManualDirectDebit_Hook_QueryObjects_Contribution in /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/ext/uk.co.compucorp.manualdirectdebit/CRM/ManualDirectDebit/Hook/QueryObjects/Contribution.php on line 20
PHP Stack trace:
PHP   1. {main}() /opt/buildkit/extern/phpunit5/phpunit5.phar:0
PHP   2. PHPUnit_TextUI_Command::main($exit = *uninitialized*) …
```
=> MAE-888: Update testing workflow to PHP 8 container

CRM/ManualDirectDebit/Form/BatchTransaction.php
A syntax error `Argument #2 must be of type array, null given in array_merge()` is thrown when no attribute is specified when adding a button element to the page. we resolve this issue by specifying an empty array as an attribute
An error page is displayed while trying to create a new instruction batch
The user is able to create new instruction batch
=> MAE-959: Fix array_merge error in PHP 8

CRM/ManualDirectDebit/Hook/Links/LinkProvider.php
"Use A New mandate" action appears for all manual direct and non manual direct debit recurring contributions (payment plans)
Here is an example of two recurring contribtions, were one is Manual direct debit and already linked to a mandate, and the other is non manual direct debit, both shows the "Use A New mandate"  option.
"Use A New mandate" action appears only for recurring contributions that are linked to a mandate:
=> CIWEMB-257: Only show 'use new mandate' action on manual direct debit payment plans

manualdirectdebit.php
Users with `administer ManualDirectDebit` are unable to delete mandates, only users with `administer CiviCRM` can do that:
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/assets/6275540/e6757927-465b-4bcb-9b92-41bb8dc580aa
Users with `administer ManualDirectDebit` are no able to delete mandates:
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/assets/6275540/f6016b78-a9ca-4c7c-9409-388a785db0d3
When the user tries to delete a mandate, an Ajax API v3 call is triggered against `ManualDirectDebit.delete` end point, which is the one responsible to delete the mandate:
https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blob/master/js/mandateEdit.js#L36-L42
And permission check is enforced by default on all API calls that are called using Ajax, and if it …
=> CIVIPLMMSR-199: Allow users with 'administer ManualDirectDebit' permission to be able to delete mandates

CRM/ManualDirectDebit/Common/SettingsManager.php
This pr fixes a bug due to which user was unable to submit a webform for creating contributions.
when user tries to submit any webform for making a reccuring contribution the user sees the following maintenance page
[This](https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blob/master/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php#L41) expects the second param as array, but when it is getting called from [here](https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blob/master/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php#L22) and [here](https://github.com/compucorp/uk.co.compucorp.manualdirectdebit/blob/master/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/FirstContribution.php#L29) it …
=> ESEB-148: Fix Submission Of Contribution Webforms

templates/CRM/ManualDirectDebit/Page/BatchTransaction.tpl
This pr fixes the broken button styles on **instruction batch** view page
=> COMCL-508: Fix Button Styles For "Instruction Batch" View Page

.github/workflows/tests.yml, CRM/ManualDirectDebit/Form/Batch.php, xml/customFields_install.xml
Resolve issue while creating direct debit batch, this is caused by the update in the latest CiviCRM version that requires the Batch form to declare entity name https://github.com/civicrm/civicrm-core/blob/cf147b8aaba4e0b842fc798f3e603cbbbf0bb267/CRM/Batch/Form/Batch.php#L22-L26
Error is no longer thrown
=> COMCL-651: Resolve issue while creating direct debit batch

.github/workflows/tests.yml, CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php
Previously users couldn't edit the direct debit mandate because the array_key_exists now throws an error if the array passed to it is null, we now check the array is empty before passing to array_key_exist
=> COMCL-842: Fix issue with editing direct debit mandate

CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php, CRM/ManualDirectDebit/Hook/Links/LinkProvider.php, templates/CRM/ManualDirectDebit/Form/InjectDirectDebitInformation.tpl
Before this PR users couldn't add a new mandate to a recurring contribution. This issue happened because the custom data edit form requires the table ID to be passed via URL if the form is opened on a standalone page.
In this PR we now open the mandate form in a popup.
=> COMCL-843: Resolve issue with adding a new mandate to recur contribution

CRM/ManualDirectDebit/Page/AJAX.php
This pr fixes the deleteion of rows from a direct debit batch.
In latest civicrm the id param is required to delete a record, but we were previously using different params other than id to delete records. This pr fixes this issue and uses the id param to delete rows from a batch.
=> COMCL-933: Fix Removal Of Records From Batch

templates/CRM/ManualDirectDebit/Page/BatchList.tpl
This pr fixes the ellipses menu on manage direct debit batches screen.
The user was not able to open the ellipses menu as nothing happened when user clicked on the menu.
The menu opens up after clicking
This error appeared due to smarty upgrade to version 4.
=> COMCL-1025: Fix Ellipses Menu
