xml/customFields_install.xml
Change Direct Debit Mandate custom group style to Tab
=> DD-5_update: Change Direct Debit Mandate custom group style to Tab

CRM/ManualDirectDebit/Form/Batch.php, templates/CRM/ManualDirectDebit/Form/Batch.tpl
Change default title for new batch and fix 'batch type' label
=> DD-17: Change default title for new batch and fix 'batch type' label

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Page/AJAX.php, CRM/ManualDirectDebit/Page/BatchList.php, CRM/ManualDirectDebit/Page/BatchTransaction.php, manualdirectdebit.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl, templates/CRM/ManualDirectDebit/Page/BatchList.tpl, templates/CRM/ManualDirectDebit/Page/BatchTransaction.tpl, xml/Menu/manualdirectdebit.xml, xml/customFields_install.xml
1. Add a new menu item Direct Debit > “View new instruction batches” and “View payment batches”
2. New menu item “View new instruction batches” leads to “ New Direct Debit Instructions Batches” page with all existing batches with batch type "New Direct Debit Instructions" listed in a table.The table has the following columns:
- Batch Name - name of the batch
- Instruction Count - the number of instructions included in the batch
- Status - status of the batch, refer to CiviCRM batch status
- Created Date - date the batch is created
- Created by - name of the user who created the batch
- Actions:
- View Instructions - allow admin to view the list of instructions in a batch
- Export - export the batch file again
- Submit (only show if the batch is "Open") - mark the batch as "Submitted"
- …
=> DD-18 & DD-19: View New instruction batches and Payment batches

CRM/ManualDirectDebit/Hook/PostProcess/Membership/DirectDebitMandate.php, CRM/ManualDirectDebit/Hook/ValidateForm/MandateValidator.php
Fix mandate 'Authorisation File' saving in membership screen
=> DD-22: Fix file saving in membership screen

CRM/ManualDirectDebit/Common/SettingsManager.php, CRM/ManualDirectDebit/Form/Configurations.php
Add cleaning cash action when getting setting values
=> DD-10: Add cleaning cash action when getting setting values

CRM/ManualDirectDebit/Hook/Links/LinkProvider.php, manualdirectdebit.php
Fix 'use new mandate' links creation.
=> DD-24: Fix 'use new mandate' links creation

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
1. Payment view link go to proper contribution modal
2. All available payments go to payment batch
=> DD-17,19: Fix payment view link and creation of payment batch

CRM/ManualDirectDebit/Upgrader.php, manualdirectdebit.php, xml/customFields_install.xml
1. Disable or Uninstall of DD extension removes the Direct Debit menu item
2. Add origination number opens one window
=> Add extension enable, disable and uninstall. Fix link to originator number

CRM/ManualDirectDebit/Upgrader.php
1. Fix issue with uninstall custom group
=> DD-36: Fix issue with uninstall custom group

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php, CRM/ManualDirectDebit/Upgrader.php, templates/CRM/ManualDirectDebit/Form/InjectCustomGroup.tpl, xml/customFields_install.xml
1. DD-38: Fix issue with enable test payment processor
2. DD-40: Fix validation error when the direct debit mandate fields are shifted below the buttons
3. DD-41: Fix regression issue with creating new batch
4. DD-36: Fix issue with uninstall
=> Fix regression issues

CRM/ManualDirectDebit/Common/DirectDebitDataProvider.php, CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/Custom/DataGenerator.php, CRM/ManualDirectDebit/Hook/Custom/Mandate/MandateDataGenerator.php, CRM/ManualDirectDebit/Hook/PostProcess/Membership/DirectDebitMandate.php, manualdirectdebit.php
Add auto generation DD-Ref in Membership form
=> DD-22: Add auto generation DD-Ref in Membership form

CRM/ManualDirectDebit/Batch/Transaction.php
Fix batch pagination and batch counting
=> DD-19: Fix batch pagination and batch counting

CRM/ManualDirectDebit/Upgrader.php
Fix issue with updating extension
=> DD-30: Fix update issue

CRM/ManualDirectDebit/Mail/DataCollector/Base.php, templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentCollectionReminder.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentSignUpNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentUpdateNotification.tpl
Fix image, date and indent in message templates
=> DD-30: Fix image, date and indent in message templates

CRM/ManualDirectDebit/Common/MandateStorageManager.php, CRM/ManualDirectDebit/Hook/PostProcess/Contribution/DirectDebitMandate.php, CRM/ManualDirectDebit/Mail/DataCollector/Base.php, manualdirectdebit.php, templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentCollectionReminder.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentSignUpNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/PaymentUpdateNotification.tpl
Fix recurring contribution activity, fix templates indent and data collection.
=> DD-31: Fix recurring contribution activity, fix templates indent and data collection

CRM/ManualDirectDebit/Upgrader.php, templates/CRM/ManualDirectDebit/Form/Configurations.hlp
Add help text in settings and remove schedule job duplicates
=> DD-32: Add help text and remove jobs duplicate

CRM/ManualDirectDebit/Common/Activity.php, CRM/ManualDirectDebit/Hook/BuildForm/CustomData.php
1. DD-22: Fix 'dd_ref' as required field
2. DD-32: Remove schedule job notice
=> DD-22: Fix dd_ref as required field & DD-32: Remove schedule job notice

CRM/ManualDirectDebit/Upgrader.php
=> DD-30/31: Update message templates

CRM/ManualDirectDebit/Hook/Custom/Contribution/ContributionDataGenerator.php
This PR fixes the calculation of next scheduled contribution date for the mandate recurring contribution so it point to the next contribution (the 2nd contribution on the payment plan).
=> BASW-104: Fix next scheduled date calculation for the recurring contribution

CRM/ManualDirectDebit/Upgrader.php
This PR fixes a fatal error that appears after disabling the extension, the extension was previously use CRM_Core_BAO_CustomGroup::setIsActive(); method to enable or disable some of the custom fields which interferes with the implementation of hook_civicrm_postSave_civicrm_custom_group hook implementation inside webform_civicrm module https://github.com/colemanw/webform_civicrm/blob/7.x-4.x/webform_civicrm.module#L421 . I fixed it by replacing the  method above call with an API call.
I also changed the user_name_label for "Offline Direct Debit" payment processor type from "Offline Direct Debit" to "User Name" and made the extension to create both live and test version of "Direct Debit" payment processor.
=> BASW-169: Fixing a fatal error during the extension disable

CRM/ManualDirectDebit/Event/Listener/TokenRender.php, manualdirectdebit.php
This PR implements the first option (Option 1: civi.token.render) mentioned in this gist : https://gist.github.com/MiyaNoctem/a93b703fcee4f65484c683a36736372e
=> DD-53: Using DD message templates with scheduled reminders

CRM/ManualDirectDebit/Mail/Task/PDFLetterCommon.php
When printing direct debit letters, the tokens which are additionally added from the token dropdown are rendered on the PDF.
Example write tokens: 
Example result tokens:
=> DD-56: Fix tokens in 'print DD Letter' action

CRM/ManualDirectDebit/Common/MessageTemplate.php, templates/CRM/ManualDirectDebit/MessageTemplate/AutoRenewNotification.tpl, templates/CRM/ManualDirectDebit/MessageTemplate/MandateUpdateNotification.tpl
In this PR : 
1- A typo in Payment Collection Reminder template title is fixed "Direct Direct Debit Payment Collection Reminder" => "Direct Debit Payment Collection Reminder" (extra "Direct")
2- Auto-renewal notification and Mandate Update Notification templates markup formats are changed to match other templates.
=> DD-58: Templates Typo and formatting fixes

CRM/ManualDirectDebit/Hook/BuildForm/Payment.php
The new mandate selection combo, loaded when choosing DD as a payment method, allows the creation of a new mandate when selecting the appropriate option. Once the new mandate is created, the field is reloaded to load the new mandate as an option. The idea now is the newly created mandate should be selected by default.
New mandate had to be selected manually, after it was created.
New mandate is selected automatically.
=>  DD-64: Select Created Mandate Automatically

CRM/ManualDirectDebit/Mail/Task/MembershipEmailCommon.php, CRM/ManualDirectDebit/Mail/Task/PDFLetterCommon.php
The fix is done quickly and urgently but it is not that great both code and business logic wise, for example The failure message should be more clear and provide more info as well as the view should probably be in a separate page instead of a pop-up notification. 
When generating DD PDF letters or sending emails from membership search, and if at least one membership selected does not have a related contribution (a MembershipPayment record) then a fatal error will appear and the rest of emails nor the PDF will be generated.
This happen because the code that generates the template data trigger an expection if no contribution found related to the selected membership, I fixed this temporarily by adding catching the exception at the Task class layer and showing a list of failed memberships …
=> ASE-306: Ensure that sending emails or letters does not crash when at least one membership does not have a related contribution

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, CRM/ManualDirectDebit/Page/AJAX.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
Added recieve date column to dd page and export csv
=> ASESPRT-80: Added receive date column to dd page and export csv

CRM/ManualDirectDebit/Batch/Transaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
**Overview**
Added contribution filters to Direct Debit Payment Create Batch page.
**Filter list**
1. Date Received
2. Contribution Amounts
3. Payment Method
4. Contribution Status
5. Transaction id
6. Invoice Number
7. Contribution or Soft Credits?
8. Contribution is pay later?
9. contribution is recurring?
10. Thank you sent
11. Receipt sent
12. Financial Type,
13. Contribution Page
14. Contribution Source.
15. Contribution Page
16. Refund Reason
17. Cancel date.
18. Personal Campaign Page
**Before**
**After**
=> DD-72: Adding contribution filters to DD create payment collection batch

CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/Batch.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, templates/CRM/ManualDirectDebit/Form/Batch.tpl, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
**Overview**
This PR set defaults values for Payment method, Contribution Status, Date Received and Contribution Recur status filters. Additionally, above fields are also disabled to prevent user from changing the
values.
**Before**
Main Screen:
Filters:
**After**
Main Screen:
Filters:
=> DD-72: Feedback changes to contribution filters on DD create payment collection batch

CRM/ManualDirectDebit/Batch/BatchHandler.php, CRM/ManualDirectDebit/Batch/Transaction.php, CRM/ManualDirectDebit/Form/BatchTransaction.php, templates/CRM/ManualDirectDebit/Form/BatchTransaction.tpl
**Overview**
This PR contains minor fixes namely, 
1. Changed receive date column label to "Received Date".
2. Changed received date column date format to dd-mm-yyyy.
3. Moved all date filter logics to respective functions (addContributionReceiveDateCondition($query) and addContributionCancelDateCondition($query))
=> DD-72: Feedback changes to contribution filters on payment batch create page. 

info.xml
DD-79: Updated version number from v1.0 to v2.0
DD-79: Updated release date.
=> DD-79: Updated release info in info.xml.

info.xml
=> DD-79: Updated info.xml information

info.xml
=> MAE-341: Bump version number to 2.3.0

info.xml
Merging rc branch back to master after 2.3.0 release
=> MAE-341: 2.3.0 Release

templates/CRM/ManualDirectDebit/Form/SetUp.tpl
This PR is for changing texts and adding missing texts on Direct Debit Setup Form.
Some texts are missing
Missing texts are added.
=> RSE-1127: Fix missing text and update direct debit text

templates/CRM/ManualDirectDebit/Form/SetUp.tpl
This PR is to fix a direct debit guarantee format.
=> RSE-1127: Fix direct debit text format

info.xml
Updating release info for Membershipextras product suite release version 2.4.0
=> MAE-384: Bump version and release info for 2.4.0

info.xml
This PR update bump version to 3.0.1.
=> MAE-385: Bump version 3.0.1

CRM/ManualDirectDebit/Upgrader.php
We decided to unify pages to manage instruction batches and payment batches in a single screen where we can use the filter to choose the type of batch we want to see. To accomplish this we need to:
1. Remove current menu options (Manage Instruction Batches / Manage Payment Collection Batches), that add a batch type to the URL.
2. Add new menu option “Manage Direct Debit Batches“
3. Re-order menu so creation items are first and manage batches option is last:
1. Create New Instructions Batch
1. Create Payment Collection Batch
1. Create Cancelled Instructions Batch
1. Manage Direct Debit Batches
Menu was disorganized, having creation items mixed with items to manage batches.
Menu is organized a per specification:
1. Create New Instructions Batch
1. Create Payment Collection Batch
1. Create …
=> IO-113: Unify Manage Batches in Single Screen

CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContribution.php, tests/phpunit/CRM/ManualDirectDebit/Hook/CalculateContributionReceiveDate/SecondContributionTest.php
On auto-renewal, and under some settings, it may happen that the second instalment of the renewed plan has its receive date moved, trying to follow the **Second Instalment Date Behaviour** setting. If it is set to force on the second month, it may be moved to a different date, which is no longer needed.
Example:
1. Update the DD configurations as below,
- New instruction run dates: 4
- Payment collection run dates: 5, 21
- Minimum days from new instruction to first payment: 3
- Second Instalment Date Behaviour: Force to the second month of membership
2. Create membership and run the auto-renewal job. Dates are displayed as below:
- Before renewal
- Membership Date: 4th August 2019  -  3rd August 2020
- 1st Instalment:  21st September 2019
- 2nd instalment: 21st September 2019
- Next …
=> IO-135: Fix Second Instalment Receive Date Calculation on Renewals

info.xml
Bump version to 4.2.0 as part of Membershipextras 4.2.0 release
=>  MAE-512: Bump version to 4.2.0

CRM/ManualDirectDebit/Mail/Task/Email/ContributionEmail.php, CRM/ManualDirectDebit/Mail/Task/Mail.php
In this PR we fix the issue of getting errors while sending direct debit notifications.
Direct debit notification fails 
Direct debit notifications succeed
Sending direct debit notifications fails on CiviCRM version >= 5.51.0 because we check the contact `preferred_mail_format` field to determine if the mail format should be text, HTML or both, but the `preference_mail_format` is no longer supported see the discussion here https://lab.civicrm.org/dev/core/-/issues/2866, so when this conditional block runs both the `$tokenText` and `$tokenHtml` variables are NULL, and NULL messages cannot be sent resulting in an error.
```php
if ($values['preferred_mail_format'] == 'Text' || $values['preferred_mail_format'] == 'Both') {
$tokenText = CRM_Utils_Token::replaceContactTokens($text, $values, …
```
=> MAE-960: Fix send direct debit email on CiviCRM versions >= 5.51.0

.github/workflows/tests.yml, info.xml
Update release info for 5.7.0 release
=> COMCL-347: Update release info for 5.7.0 release

info.xml
=> COMCL-458: Bump version to 6.2.0

info.xml
=> COMCL-517: Bump version for 6.4.0 release

info.xml
COMCL-566: Bump version for 6.5.0 release
=> COMCL-566: Bump version for 6.5.0

CRM/ManualDirectDebit/Hook/BuildForm/CustomDataByType.php
This pr fixes an issue that restricted user from saving an event information.
=> COMCL-659: Fix Event Creation

CRM/ManualDirectDebit/Page/AJAX.php, info.xml
COMCL-907: Merge rc branch to master
=> COMCL-907: Merge Rc Branch to Master

templates/CRM/ManualDirectDebit/Form/SetUp.tpl
This pr fixes errors that arised when smarty engine was upgraded to version 4.
=> COMCL-954: Add Fixes For Smarty4

info.xml, templates/CRM/ManualDirectDebit/Form/SetUp.tpl, templates/CRM/ManualDirectDebit/Page/BatchList.tpl, templates/CRM/ManualDirectDebit/Page/BatchTransaction.tpl
This pr upgrades the version to 6.8.0
=> COMCL-1020: Bump Version

info.xml
Bump version for 6.8.1 release
=> COMCL-1103: Bump version for 6.8.1 release
